<?php 

/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else
{ ?>
 <style type="text/css">
.invfrnds_confirm{width:900px !important; height:522px !important;}
.white_content{top: 10% !important; position: fixed !important;}
</style>
<?php 
	if (count($this->messages)) {?>
	<div id="dispmsgsddept">
    <?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
	?>
	</div>	
	
<?php } ?>
<form name="assigngroupid" id="formid" action="" method="post">
<input type="hidden" name="empids" id="empids" value="">
<div class="total-form-controller">
<div class="new-form-ui">
								<div class="new-form-ui radioclass">
					            <label class="required">Configure Questions </label>
					            <div class="division">
								<label for="service_desk_flag-1">
									<input type="radio" onclick="hideshowgroups(this)"  value="1" id="group_flag-1" name="group_flag">
									All
								</label>
								<label for="service_desk_flag-0">
								<input type="radio" onclick="hideshowgroups(this)" value="0" id="group_flag-0" name="group_flag">
									Configure Groups
								</label>                            
								</div>
        						</div>
</div>
<div class="new-form-ui " id="groupaccordion">
	<?php if(!empty($this->appraisalgroupName)){
			foreach($this->appraisalgroupName as $key => $val){
	?>
	<div class="cls_headers">
	<?php echo $val['group_name']?>
		
				<input type="hidden" id="idhidgroupid<?php echo $key;?>" value="<?php echo $val['id'];?>" class="hidemp_ac" />
	  </div> <div> hgfhgfhgfhgf</div>			
					 
				  
	<?php }}?>
</div>

<div class="new-form-ui" id="groupdropdown">
								 <label class="required">Select Group </label>
									<div class="division">
									<select id="group_id" name="group_id" tabindex="-1" onclick="javascript:fetchgroupdata(this);">
										<?php echo $this->options;?>
									</select>							
									</div>	
</div>
<input type="hidden" id="appraisalid" name="appraisalid" value="<?php echo $this->appraisalid;?>">


		<div class="content_box add_new_fields checklist_new_fields action_buttons_div">
		
			<span id="no_members_error" style="display:none;color: red; position: absolute; font-size: 12px; margin-left: 4px;"></span>
			<div id="actionButtonsDiv" class="new-form-ui-submit mrgetop60">  
			
			<input type="button" name="saveFiled" id="saveFiled" class="raise_button" value="Save" onclick="javascript:fnSaveMappedEmployees();" /> &nbsp;
			
			<input type="button" name="saveFiled" id="saveFiled" class="raise_button" value="Next" onclick="alert('Next step')" /> &nbsp; 
		
			<button onclick="window.location.href='<?php echo $this->baseUrl();?>/appraisalinit';" type="button" id="Cancel" name="Cancel">Cancel</button>
			</div>
		
		
		</div>
</div>
</form>
<script type="text/javascript" language="javascript">

$(document).ready(function()
{
	$('#idclear').hide();
		
	if($.trim($('#search_emp_by_name').val()).length>0)
	{
		$('#idclear').show();
	}
	else
	{
		$('#idclear').hide();
	}
	
	$(document).keyup(function(e) {	 
	  if (e.keyCode == 27) { closeconfirmPopup(); }   // esc
	});


	$( "#groupaccordion" ).accordion({
        collapsible: true,
        active:false,
        heightStyle: "content",
        beforeActivate: function( event, ui ) {    
            var empid=ui.newHeader.find('.hidemp_ac').val();
            var appraisalid=$('#appraisalid').val(); 
            console.log(ui.newHeader.find('.hidemp_ac').val()); 
            console.log(empid+'<>'+appraisalid);
            if(empid!=null)
            {                            
                 $.get(base_url+'/appraisalinit/getempdetails/format/html/empid/'+empid+'/appraisalid/'+appraisalid,function(data){
                        ui.newPanel.html(data);
                    },'html');
            }
        },
        header:'.cls_headers'
    });//end of accordion function 

});


$('#search_emp_by_name').bind('keyup', function() {

	var txt = $.trim($('#search_emp_by_name').val());
	$('div.users_left_list').hide();
    $('div.users_left_list').each(function(){
       if($(this).attr("name").toUpperCase().indexOf(txt.toUpperCase()) != -1){
           $(this).show();
       }
    });
	
	if($('div.users_left_list:visible').length < 1)
	{
		$('div.no_search_results').show();
	}
	else
	{
		$('div.no_search_results').hide();
	} 
	
	if(txt.length>0){
		$('#idclear').show();
		$(".no_left_data_found").hide();
	}else{ 
		$('#idclear').hide();
		
	}
});

$('#search').bind('click', function() {

	var txt = $.trim($('#search_emp_by_name').val());
	$('div.users_left_list').hide();
    $('div.users_left_list').each(function(){
       if($(this).attr("name").toUpperCase().indexOf(txt.toUpperCase()) != -1){
           $(this).show();
       }
    });
	
	if($('div.users_left_list:visible').length < 1)
	{
		$('div.no_search_results').show();
	}
	else
	{
		$('div.no_search_results').hide();
	} 
	
	if(txt.length>0){
		$('#idclear').show();
		$(".no_left_data_found").hide();
	}else{ 
		$('#idclear').hide();
	}
});
//$('.users_list_left').alternateScroll({ 'horizontal-bar-class': 'styled-h-bar'});

//$('.users_list_right').alternateScroll({ 'horizontal-bar-class': 'styled-h-bar'});

function clearSearchData()
{	
	$('#search_emp_by_name').val('');
	$('#idclear').hide();
	
	var txt = $.trim($('#search_emp_by_name').val());
	$('div.users_left_list').hide();
    $('div.users_left_list').each(function(){
       if($(this).attr("name").toUpperCase().indexOf(txt.toUpperCase()) != -1){
           $(this).show();
       }
    });
	
	$('div.no_search_results').hide();
}
</script>

<?php }?>	