<?php 

/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else
{ ?>
 <style type="text/css">
.invfrnds_confirm{width:900px !important; height:522px !important;}
.white_content{top: 10% !important; position: fixed !important;}
</style>
<?php 
	if (count($this->messages)) {?>
	<div id="dispmsgsddept">
    <?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
	?>
	</div>	
	
<?php } ?>
<form name="assigngroupid" id="formid" action="" method="post">
<input type="hidden" name="empids" id="empids" value="">
<div class="total-form-controller">

<div class="new-form-ui clearb">
								 <label class="required">Select Group </label>
									<div class="division">
									<select id="group_id" name="group_id" tabindex="-1" onclick="javascript:fetchgroupdata(this);">
										<?php echo $this->options;?>
									</select>							
									</div>	
</div>
<input type="hidden" id="appraisalid" name="appraisalid" value="<?php echo $this->appraisalid;?>">
<div class="invfrnds_confirm">
	<div class="popup_header">
		<h1 class="popups_child_headers">Add Project Employees </h1>

		<div class="search_emp_by_name_div">
			<input type="text" name="search_emp_by_name" id="search_emp_by_name" value="" placeholder="Search Employee"/>
			<input type="button" value="Go" name="search" id="search">&nbsp;
			<input type="button" id="idclear" name="tclear" value="Clear" class="btn_search_clear" onclick="javascript:clearSearchData();"/>
			
		</div>
			
	</div>
	
	<span id="success_users_message" style="display:none;  margin-left: 5px;" class="green_color_text"></span>

<div class="clear"></div>

<div class="users_list">

<div class="left-user">
<div class="users_list_left_title">Employees (Click on an employee to add to project)</div>

<div class="users_list_left" >

<?php
if(count($this->employeeList) > 0)
{
	$isUser = 0;
	foreach($this->employeeList as $emp)
	{
			?>
			<div class="users_left_list_div users_left_list user_div_<?php echo $emp['user_id'];?>" subject = '<?php echo $emp['user_id'];?>' style="cursor:pointer;" onclick="javascript:fnAddRemoveProjectUser(1,'<?php echo $emp['user_id'];?>','<?php echo addslashes($emp['userfullname']);?>','<?php echo $emp['profileimg'];?>');" alt="Add" title="Add" name="<?php echo addslashes($emp['userfullname']);?>">
			<span class="values">
			<div class="profile_img">
			<img src="<?php echo $this->baseUrl("public/uploads/profile/").$emp['profileimg'];?>" width="28px"  height="28px" onerror="this.src='<?php echo MEDIA_PATH; ?>images/default-profile-pic.jpg'"/>
			</div> </span> <span class="member_name"><?php echo $emp['userfullname'];?>
			</span>
			</div>
			<?php
			$isUser++;
	}
	if($isUser < 1)
	{
		?>
		<div class="users_left_list_div no_left_data_found"><span class="values">Employees are not available.</span></div>
		<?php		
	}
		
}
else
{
?>
	<div class="users_left_list_div no_left_data_found" ><span class="values">Employees are not available.</span></div>
<?php
}
?>

<div class="users_left_list_div  no_search_results" style="display:none"><span class="values">No results were found.</span></div> 

</div>
</div>
<div class="left-user">
<div class="users_list_right_title">Project Employees (Click on an employee to remove from project)</div>

<div class="users_list_right">


<div class="users_right_list_div no_right_data_found"><span class="values">Add employees to project.</span></div>



</div>

</div>

<input type="hidden" name="mem_list_str" id="mem_list_str" value="" />

<input type="hidden" name="existetd_mem_str" id="existetd_mem_str" value="" />

</div>




</div>

		<div class="content_box add_new_fields checklist_new_fields action_buttons_div">
		
			<span id="no_members_error" style="display:none;color: red; position: absolute; font-size: 12px; margin-left: 4px;"></span>
			<div id="actionButtonsDiv" class="new-form-ui-submit mrgetop60">  
			
			<input type="button" name="saveFiled" id="saveFiled" class="raise_button" value="Save" onclick="javascript:fnSaveMappedEmployees();" /> &nbsp;
			
			<input type="button" name="saveFiled" id="saveFiled" class="raise_button" value="Next" onclick="alert('Next step')" /> &nbsp; 
		
			<button onclick="window.location.href='<?php echo $this->baseUrl();?>/appraisalinit';" type="button" id="Cancel" name="Cancel">Cancel</button>
			</div>
		
		
		</div>
</div>
</form>
<script type="text/javascript" language="javascript">

$(document).ready(function()
{
	$('#idclear').hide();
		
	if($.trim($('#search_emp_by_name').val()).length>0)
	{
		$('#idclear').show();
	}
	else
	{
		$('#idclear').hide();
	}
	
	$(document).keyup(function(e) {	 
	  if (e.keyCode == 27) { closeconfirmPopup(); }   // esc
	});

});


$('#search_emp_by_name').bind('keyup', function() {

	var txt = $.trim($('#search_emp_by_name').val());
	$('div.users_left_list').hide();
    $('div.users_left_list').each(function(){
       if($(this).attr("name").toUpperCase().indexOf(txt.toUpperCase()) != -1){
           $(this).show();
       }
    });
	
	if($('div.users_left_list:visible').length < 1)
	{
		$('div.no_search_results').show();
	}
	else
	{
		$('div.no_search_results').hide();
	} 
	
	if(txt.length>0){
		$('#idclear').show();
		$(".no_left_data_found").hide();
	}else{ 
		$('#idclear').hide();
		
	}
});

$('#search').bind('click', function() {

	var txt = $.trim($('#search_emp_by_name').val());
	$('div.users_left_list').hide();
    $('div.users_left_list').each(function(){
       if($(this).attr("name").toUpperCase().indexOf(txt.toUpperCase()) != -1){
           $(this).show();
       }
    });
	
	if($('div.users_left_list:visible').length < 1)
	{
		$('div.no_search_results').show();
	}
	else
	{
		$('div.no_search_results').hide();
	} 
	
	if(txt.length>0){
		$('#idclear').show();
		$(".no_left_data_found").hide();
	}else{ 
		$('#idclear').hide();
	}
});
$('.users_list_left').alternateScroll({ 'horizontal-bar-class': 'styled-h-bar'});

$('.users_list_right').alternateScroll({ 'horizontal-bar-class': 'styled-h-bar'});

function clearSearchData()
{	
	$('#search_emp_by_name').val('');
	$('#idclear').hide();
	
	var txt = $.trim($('#search_emp_by_name').val());
	$('div.users_left_list').hide();
    $('div.users_left_list').each(function(){
       if($(this).attr("name").toUpperCase().indexOf(txt.toUpperCase()) != -1){
           $(this).show();
       }
    });
	
	$('div.no_search_results').hide();
}
</script>

<?php }?>	