<?php 

/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
$this->performancesteps();
?>
<label>Set line managers</label>
<input type="radio" name="choose_option" class="rd_choose_option" id="id_set_l1" value="line" />
<label>Set reporting managers</label>
<input type="radio" name="choose_option" class="rd_choose_option" id="id_set_report" value="report" />


<script type="text/javascript">
$(document).ready(function(){
    $('.rd_choose_option').change(function(){
        var val = $(this).val();
        console.log(val);
    });
});
</script>
