<?php 

/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/

$init_id = $this->init_id;
$init_data = $this->init_data;
?>
<?php if($init_data['initialize_status']==1) { ?>
	<div style="clear: both;position: relative; margin-bottom: 7px; width: 92%;" class="ml-alert-1-info">
						<div class="style-1-icon info"></div>
							Line Manager(s) cannot be edited as appraisal process is inititialized.
	</div>
<?php } ?>

<div id="id_acc_container">  
    
</div>
<script type="text/javascript">
construct_rep_accordion('<?php echo $init_id;?>');    
$(document).ready(function(){
	$("#info_message").html('Configure Line Managers by Organization Hierarchy');
});//end of ready function
</script>