<?php 

/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div><?php echo $this->ermsg;?></div>
<?php 
}
else
{
    $this->performancesteps();
    sapp_Global::generateClientValidations($this->form);
    $imple_data = $this->imple_data;
    $performance_app_flag = $imple_data['performance_app_flag'];
    $request = Zend_Controller_Front::getInstance();
    $actionName = $request->getRequest()->getActionName();
    if($actionName == 'view')
        $viewclass = 'view-form-detail';
    else
        $viewclass = '';  

    $departmentArr = array(); 
 	 	  
 ?>
     <input type="hidden" id="idhid_bunit" value="<?php echo $imple_data['businessunit_id'];?>" />
<div id="error_message" style="display:none;"></div>
<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
		<?php echo $this->form->businessunit_id; ?>
    <input type="hidden" name="configuration_id" value="<?php echo $imple_data['id'];?>" />
		<?php echo $this->form->department_id; ?>
        <div class="total-form-controller <?php echo $viewclass;?>">
        	<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'businessunit_name','', '','',array());?>
        	<?php 
                if($performance_app_flag == 0)
                echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'department_name','', '','',array());
                ?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'appraisal_mode','', '','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'from_year','', '','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'to_year','','','required',array());?>
                        <?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'appraisal_period','','','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'status','','','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'eligibility','','','required',array());?>
			<?php echo sapp_Helper::sd_form_helper($this->msgarray, $this->form, 'enable_step','','','required',array());?>						
					
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<?php if($actionName == 'view'){?>
			<input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
		<?php }?>
		<button onclick="window.location.href='<?php echo $this->baseUrl();?>/appraisalinit';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
	</div>
</form>

	<?php echo sapp_Helper::popup_helper('appraisalinit');?>
	
<?php }?>
<script type='text/javascript'>
$(document).ready(function(){		            
    $('#from_year,#to_year').change(function(){
        year_change();
    });
});//end of ready function
function year_change()
{
    var from_val = $('#from_year').val();
    var to_val = $('#to_year').val();
    $('#appraisal_period').val('');
    if(from_val !== '' && to_val !== '')
    {
        to_val = parseFloat(to_val);
        from_val = parseFloat(from_val);
        if(from_val > to_val)
        {
            $('#to_year').val('');
            apply_select2();
            $('#to_year').parent().append('<span id="errors-from_year" class="errors">From year must be less than to year</span>');
        }
        else
        {
            var bunit = $('#idhid_bunit').val();
            var amode = $('#appraisal_mode').val();
            $.post(base_url+"/appraisalinit/getperiod",{from_year:from_val,to_year:to_val,bunit:bunit,mode:amode},function(data){
                if(data.status === 'success')
                {
                    $('#appraisal_period').val(data.val);
                }                    
            },'json');
        }
    }
}


<?php if(!$_POST){ ?>
	var eligibility_value = '<?php echo $this->eligibility_value;?>';
	if(eligibility_value !='')
	{	
		var errorMsg = "<?php if(isset($this->msgarray['eligibility'])) echo $this->msgarray['eligibility'];?>";
		var eligibility_Arr = eligibility_value.split(",");
		var eligibility_Data = document.getElementById('eligibility');
		for(var j = 0 ; j <= eligibility_Arr.length ; j++)
		{	
			for(var i = 0 ; i <= eligibility_Data.length ; i++)
			{
				if(eligibility_Data.options[i] !== undefined)
				{
					if(eligibility_Data.options[i].value === eligibility_Arr[j]) 
					{
						if(errorMsg != '' && errorMsg != 'undefined')
						{	
							eligibility_Data.options[i].selected = false;
						}	
						else
						{	
							eligibility_Data.options[i].selected = true;
						}	
						break;
					}
				}
			}
		}
	}	
	
<?php } ?>	

</script>