<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
 	

if (count($this->messages)) {?>
	<div id="dispmsgemp" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>	
	
<?php }	
if($this->dataArray[0]['emptyroles'] == 1)
{
 ?>
	 <div class="ml-alert-1-info m1-info-set">
		<div class="style-1-icon info"></div>
			Employees grid will not work as Roles are not added yet.
	</div>
 <?php	} else	{	?>

<?php
if($this->call != 'ajaxcall')
{
    if(!empty($this->popConfigPermission))
    {
?>
<div>

<!-- For excel Upload -->
<div class="profile-tabs-right-2">
    <div class="flt_right">
      	
        <div class="actions_div">

            <span class="uploadbut_exel uploadbutsel flt_left marginfiv" id="upload_custom_div" >Import Employees</span>
			<a target="_blank" href="<?php echo DOMAIN; ?>public/downloads/import_employees.xlsx" class="importformatlink flt_left">Import format</a>
            <div id="loaderimgprofile" style="display:none;"><img src="<?php echo $this->baseUrl("public/media/images/loaderwhite_21X21.gif");?>" style="width:21px; height: 21px; float: none; "/></div>								
        </div>                 					
    </div>
    <input type="hidden" id="uploadimagepath" name="uploadimagepath" value=""/>
    <input type="hidden" name="emp_excel" value=""/>							    	
               				                        					
</div>
</div>

<span id="error_message"></span>
<div id="upload_error" style="display:none;clear:both;"></div>	
<!-- End excel Upload -->
<?php
    }
}
 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->employeegrid($this->dataArray[0]).$endDiv;
?>
<?php	}	?>
<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgemp').fadeOut('slow');
		},3000);

<?php } ?>

})
</script>

<?php 
if($this->call != "ajaxcall")
{
    if(!empty($this->popConfigPermission))
    {
?>
<script type="text/javascript">

var btnUpload = $('#upload_custom_div');
new AjaxUpload(btnUpload, {

	action :  base_url+'/employee/uploadexcel',
	name   : 'emp_excel',  //we can rename it 
	dataType: 'json',
	onSubmit: function(file,ext){
	if($("#upload_error").is(":visible"))
	 $("#upload_error").hide();
	  $("#loaderimgprofile").show();
									 
	},
	onComplete: function(file, response){
	    var result = JSON.parse(response);
      	if(result.result == 'success')
		{
                        
			$('#upload_error').show();
			$("#loaderimgprofile").hide();
            $('#upload_error').html('<div  class="ml-alert-1-success"><div style="display:block;"><span class="style-1-icon success"></span>'+result.msg+'</div></div>');
            setTimeout(function()
			{
               $('#upload_error').fadeOut('slow');
               location.reload();
			},3000);
		}
		else
		{
			$('#upload_error').show();
			$("#loaderimgprofile").hide();
			if(result.msg)
			 $('#upload_error').html('<div  class="ml-alert-1-error"><div style="display:block;"><span class="style-1-icon error"></span>'+result.msg+'</div></div>');
			else
			 $('#upload_error').html('<div  class="ml-alert-1-error"><div style="display:block;"><span class="style-1-icon error"></span>Please choose different file.</div></div>');								
		}
	}	
},'json');
</script>
<?php 
}
}
?>

