<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
        <div class="total-form-controller view-form-detail">
		    <div class="new-form-ui ">
				<label><?php echo $this->form->department->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->department; ?></div>
			</div>
			
			<div class="new-form-ui ">
				<label><?php echo $this->form->jobtitleid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->jobtitleid; ?></div>
			</div>
			
		 	<div class="new-form-ui ">
			  <label><?php echo $this->form->positionheld->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->positionheld; ?></div>
			</div>
			
			<div class="new-form-ui ">
			    <label><?php echo $this->form->start_date->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->start_date; ?></div>
			</div>
				
			<div class="new-form-ui ">
			  <label><?php echo $this->form->end_date->getLabel(); ?></label>
			  <div class="division"><?php echo $this->form->end_date; ?></div>
			</div>
			
			<!--<div class="new-form-ui ">
			  <label><?php //echo $this->form->active_company->getLabel(); ?></label>
				<div class="division"><?php //echo $this->form->active_company; ?></div>
			</div>-->

        <div class="new-form-ui-submit" id="formSubmit">
         <!--<button onclick="closeiframepopup('empskills','cancel');" type="button">Cancel</button>-->
         <input onclick="closeiframepopup('empjobhistory','cancel');" type="button" value="Close"  />
        </div>
 

</div>       
        