<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>
<?php 
$auth = Zend_Auth::getInstance();
if($auth->hasIdentity())
{
 $loginUserId = $auth->getStorage()->read()->id;
 $loginuserRole = $auth->getStorage()->read()->emprole;
 $loginuserGroup = $auth->getStorage()->read()->group_id;
}

if($loginuserGroup==MANAGER_GROUP || $loginuserGroup==MANAGEMENT_GROUP || $loginuserRole==SUPERADMINROLE)
            {
			if($this->call != 'ajaxcall'){
?>
				<div class="flt_right"  style="clear: both;">
					<div class="actions_div">
						<a class="importformatlink flt_left" href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/myemployees/employeereport">My Team Report</a>
					</div>	
				</div>
<?php 
            }
			}
?>
<?php if (count($this->messages)) {?>
	<div id="dispmsgmyemp" class="settingssuccess">
		<?php foreach ($this->messages as $message){?>
		 <?php echo $this->escape($message); ?>
		<?php } ?>
	</div>	
	
<?php } ?>
<span id="error_message"></span>
<?php if($this->dataArray[0]['emptyroles'] == 1)
{
 ?>
	 <div class="ml-alert-1-info m1-info-set">
		<div class="style-1-icon info"></div>
		My Team grid will not work as Roles are not added yet.
	</div>
 <?php	} else	{	

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;

}
	?>

<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgmyemp').fadeOut('slow');
		},3000);

<?php } ?>

})
</script>

