<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/

if($this->ermsg == '')  
{
	/* Start Performance Header Conditions */
	if(isset($this->data['id']) && $this->data['id']!='')
	{
		$appraisalid = $this->data['id'];
	    $step1status = 'Completed';
	}    
	else
	{
		$step1status = 'In Progress';
		$appraisalid = '';
	}
	if(isset($this->data['manager_level_type']) && $this->data['manager_level_type']!='')	
		$step2status = 'Completed';
	else
		$step2status = 'In Progress';	    
	if(isset($this->data['initialize_status']) && $this->data['initialize_status'] == 1) 
		$step3status = 'Completed';
	else
		$step3status = 'In Progress';
	$currentpage = 'initstep_1';	
	$context = 'view';
	$ratingsflag = $this->ratingsflag;		
	$perf_array = array('appraisalid'=>$appraisalid,'step1status'=>$step1status,'step2status'=>$step2status,'step3status'=>$step3status,'currentpage'=>$currentpage,'context'=>$context,'ratingsflag'=>$ratingsflag);
	$this->performancesteps($perf_array);
	/*End Performance Steps */
	
    $init_id = $this->init_id;
    $counter = 0;
 ?>
    <div class="requisitions-block_ appri_view_step_1">
        <div class="total-form-controller cancel-set data-view-details" style="padding-top: 0px;">
            
			<div class="cofig_title" style="margin-left: 0px; padding-top: 0px;">Appraisal Details
				<div class="new-form-ui-submit "  style="margin-top: 0px; float: right; width: auto;">
					<div class="back-to-page" style="position: relative; float: right; top: 0px;">
						<input type="button" onclick="window.location.href='<?php echo $this->baseUrl();?>/appraisalinit';" name="Back" value="Back" style="margin-right: 0px;">
					</div>
					<?php
					if($this->data['status']==1)
					{
						if($this->previ_data == 'Yes')
						{
						?>
							<input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />   
						<?php 
						}
					}
					?>						
	            </div></div>
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table view-table-data">
				<tr class="req-bg-form">
					<td width="20%"><span class="head_txt">Business Unit </span></td>
					<td width="30%"><?php echo $this->data['unitname'];?></td>
					<td width="20%"><span class="head_txt">Department </span></td>
					<td width="30%"><?php echo $this->data['deptname']!=''?$this->data['deptname']:"--";?></td>
				</tr>
				<tr  class="req-no-form">
					<td><span class="head_txt">Appraisal Mode </span></td>
					<td><?php echo $this->data['appraisal_mode'];?></td>
					<td><span class="head_txt">From Year </span></td>
					<td><?php echo $this->data['from_year'];?></td>
				</tr>
				<tr class="req-bg-form">
					<td><span class="head_txt">To Year </span></td>
					<td><?php echo $this->data['to_year'];?></td>
					<td><span class="head_txt">Period </span></td>
					<td><?php 
					if($this->data['appraisal_mode'] == 'Quarterly')
						echo "Q".$this->data['appraisal_period'];
					else if($this->data['appraisal_mode'] == 'Half-yearly')
						echo "H".$this->data['appraisal_period'];
					else echo "Yearly";
					?></td>
				</tr>
				<tr class="req-no-form">
					<td><span class="head_txt">Eligibility  </span></td>
					<td><?php echo isset($this->data['eligibility_names'])?strtr($this->data['eligibility_names'], array (',' => ', ')):'';?></td>
					<td><span class="head_txt">Parameters </span></td>
					<td><?php  echo isset($this->data['category_names'])?strtr($this->data['category_names'], array (',' => ', ')):''; ?></td>
				</tr>
				
				<tr  class="req-bg-form">
					<td>Status <b></b></td>
					<td>
<?php
$status = array(1 => "Open", 2 => "Closed", 3 => "Force Closed");
echo $status[$this->data['status']];
?>
					</td>
					<td><span class="head_txt">Process Status </span></td>
					<td><?php echo $this->data['process_status'];?></td>
				</tr>
				<tr class="req-no-form">
					<td><span class="head_txt">Managers' Due Date </span></td>
					<td><?php echo (!empty($this->data['managers_due_date'])) ? sapp_Global::change_date($this->data['managers_due_date'],'view') : "--"; ?></td>
					<td><span class="head_txt">Employees' Due Date </span></td>
					<td><?php echo (!empty($this->data['employees_due_date'])) ? sapp_Global::change_date($this->data['employees_due_date'],'view') : "--"; ?></td>
				</tr>  
				<tr class="req-bg-form">
					<td><span class="head_txt">Appraisal Ratings </span></td>
					<td><?php echo $this->data['appraisal_ratings']==1?'1-5':'1-10';?></td>
					<td colspan="2"></td>
				</tr>
			</table>
        </div>
    </div>

<?php }
else
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php     
}
?>

</div><!-- end of steps -->