<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}else{


	 if(!empty($this->employeedata))
	 {
			echo $this->employeedetails($this->employeedata,'mydetails',$this->id); 
	 } 
	 
?>

<div class="right-block-data">
	<div id="error_message" style="display:none;"></div>

			<?php echo $this->form->id;
			echo $this->form->user_id;
			?>
			<div class="total-form-controller cancel-set view-form-detail">
			    <div class="new-form-ui">
				  <label>Gender</label>
				<div class="division"><?php echo $this->form->genderid; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label>Marital Status</label>
				<div class="division"><?php echo $this->form->maritalstatusid; ?></div>
				</div>
		
				<div class="new-form-ui">
			   <label>Nationality</label>
				<div class="division"><?php echo $this->form->nationalityid; ?></div>
				</div>
				
				<div class="new-form-ui">
			   <label><?php echo $this->form->ethniccodeid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->ethniccodeid; ?></div>
				</div>
				
				<div class="new-form-ui">
			   <label><?php echo $this->form->racecodeid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->racecodeid; ?></div>
				</div>
				
				<div class="new-form-ui">
			   <label><?php echo $this->form->languageid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->languageid; ?></div>
				</div>
				
				<div class="new-form-ui">
				  <label>Date of Birth</label>
				<div class="division"><?php echo $this->form->dob; ?></div>
				</div>
				<!-- 								
				<div class="new-form-ui">
				  <label >Celebrated Date of Birth</label>
				<div class="division"><?php //echo $this->form->celebrated_dob; ?></div>
				</div>
				 -->
				<div class="new-form-ui">
				  <label >Blood Group</label>
				<div class="division"><?php echo $this->form->bloodgroup; ?></div>
				</div>
				
				<?php if(!empty($this->identitydocument)) {?>
				
				        <div class="separetor-heading">Identity Documents</div>
						<div id = 'parent'>      
				        <?php for($i=0;$i<sizeof($this->identitydocument);$i++){
				        ?>
				         
					         <?php 	
					         	    $totalvalue = '';
			         	    		$documentValue = '';
			         	    		$expiredateValue = ''; 
		         	    		 	if(!empty($this->documentsArr))
					         	    {
					         	    	if(array_key_exists($this->identitydocument[$i]['id'], $this->documentsArr))
					         	    	{
					         	    		$totalvalue = explode(':', $this->documentsArr[$this->identitydocument[$i]['id']]);
					         	    		$documentValue = $totalvalue[0];
					         	    		$expiredateValue = sapp_Global::change_date($totalvalue[1],'view'); 
					         	    	}
					         	    }	
						         	  
					         ?>
					        <div class="new-form-ui">
							  <label class=''><?php echo ucfirst($this->identitydocument[$i]['document_name']);?></label>
								<div class="division">
									<input type="text"  onfocus="this.blur()" readonly="readonly" value="<?php echo $documentValue;?>" >
								</div>
							</div>
							
							<?php if($this->identitydocument[$i]['expiry'] == 1){?>
										<div class="new-form-ui ">
									   	 <label ><?php echo ucfirst($this->identitydocument[$i]['document_name']).'-Expiry Date';?> </label>
											<div class="division">
												<input type="text" onfocus="this.blur()" readonly="readonly" value="<?php echo $expiredateValue;?>" >
											</div>
										</div>
										
										<?php }?>
							       <?php } ?>
							</div>
							<?php }?>
				
			</div>
            <div class="new-form-ui-submit">
			<?php	/*	If the login employee has edit privilege then show edit ...		*/
			if($this->editPrivilege == 'Yes')	{	?>
        	<input type="button" onclick="redirecttoEditscreen('<?php echo $this->controllername;?>','<?php echo $this->actionname;?>');" value="Edit" />    
		<?php	}	?>
			</div>  
	

</div>	
</div>


<script type='text/javascript'>
$(document).ready(function(){

    /* Making window responsive*/
 	var complete_empwidth = $('.emp-screen-view').width();
	$('#displayimg').css("width", "150");
	$('#personalDetailsDiv').css("width", (complete_empwidth-(152)));	
		
	 function checkempWidth() {
        var complete_empwidth = $('.emp-screen-view').width();		
		$('#displayimg').css("width", "150");
		$('#personalDetailsDiv').css("width", (complete_empwidth-(152)));		
    }
    
	$(window).resize(function() {
		checkempWidth();
	}); 

   $("#emppersonaldetails").addClass('active');
   $("#emppersonaldetails").removeAttr("onclick");

})
</script>
<?php }?>
