<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 

$user_id = $this->user_id;
if($this->popup == 'close') { ?>	
	<div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
	Organization head <?php echo $this->eventact; ?> successfully.
	</div>

<?php } 
else
{ ?>
<?php sapp_Global::generateClientValidations($this->form);?>

<div class="total-form-controller">
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>" enctype="multipart/form-data" >
		<?php echo $this->form->id; ?>
    <input type="hidden" name="user_id" value="<?php echo $user_id ;?>" />
	<input type="hidden" name="prevheadid" id="prevheadid" value="<?php echo $this->prevorgheadId;?>" />
		<?php if(isset($this->prevorgheadId) && $this->prevorgheadId != '') {  ?>
		<div id="oldreportingdiv">
		<?php if(!empty($this->orgheadsData) && $this->orgheadsData[0]['id'] != $this->prevorgheadId) { ?>
		<div><span class="">Please assign a Reporting manager to the current organization head.</span></div>
		<?php } else {?>
		<div class="ml-alert-1-info m1-info-set alert-info-set">
		<div class="style-1-icon info"></div>
			<i>There are no reporting managers to assign to the current organization head. Please add employees under management group from Human Resources >> Employees >> Add</i>
		</div>		
		<?php } ?>
		<div class="new-form-ui">
		  <label class="required">Reporting manager </label>
			<div class="division">
				<select name="prevorghead_rm" id="prevorghead_rm">
						<option value="">Select Reporting manager</option>
						<?php
						if(count($this->orgheadsData) > 0)
						{
							foreach($this->orgheadsData as $opt)
							{
								if($this->posted_prevorghead_rm == $opt['id'])
								$selectedval = 'selected';
								else 
								$selectedval = '';
								if($this->prevorgheadId != $opt['id'])
								{
							?>
							<option value="<?php echo $opt['id'];?>" <?php echo $selectedval;?> title="<?php echo $opt['profileimg'];?>"><?php echo $opt['name'];?></option>
							<?php  
								}
							}
						}
						?>
				</select>
				<?php if(isset($this->msgarray['prevorghead_rm'])){?>
					<span class="errors" id="errors-<?php echo $this->form->prevorghead_rm->getId(); ?>"><?php echo $this->msgarray['prevorghead_rm'];?></span>
				<?php }?>
			</div>	  
		</div>
		</div>
		<?php } ?>
		<div class="separetor-heading"><span class="">Management Details</span></div>
<!-- start of organisation head details -->
	
	<div class="new-form-ui">
        <label class="required"><?php echo $this->form->employeeId->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->employeeId; ?>                   
        <?php if(isset($this->msgarray['employeeId'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->employeeId->getId(); ?>"><?php echo $this->msgarray['employeeId'];?></span>
        <?php }?>
        
        </div>
    </div>
	
	<!-- <div class="new-form-ui">
	  <label class="required">Organization Head </label>
		<div class="division"><?php //echo $this->form->orghead; ?>			
			<?php // if(isset($this->msgarray['orghead'])){?>
				<span class="errors" id="errors-<?php //echo $this->form->orghead->getId(); ?>"><?php //echo $this->msgarray['orghead'];?></span>
			<?php // }?>			
		</div>	   
	</div>-->
	<div class="new-form-ui">
	  <label class="required">First Name </label>
		<div class="division"><?php echo $this->form->firstname_orghead; ?>			
			<?php if(isset($this->msgarray['firstname_orghead'])){?>
				<span class="errors" id="errors-<?php echo $this->form->firstname_orghead->getId(); ?>"><?php echo $this->msgarray['firstname_orghead'];?></span>
			<?php }?>			
		</div>	   
	</div>
	<div class="new-form-ui">
	  <label class="required">Last Name </label>
		<div class="division"><?php echo $this->form->lastname_orghead; ?>			
			<?php if(isset($this->msgarray['lastname_orghead'])){?>
				<span class="errors" id="errors-<?php echo $this->form->lastname_orghead->getId(); ?>"><?php echo $this->msgarray['lastname_orghead'];?></span>
			<?php }?>			
		</div>	   
	</div>
	
    <div class="new-form-ui">
        <label class="required"><?php echo $this->form->prefix_id->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->prefix_id; ?>
                <?php if(isset($this->msgarray['prefix_id'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->prefix_id->getId(); ?>"><?php echo $this->msgarray['prefix_id'];?></span>
        <?php }?>        
        </div>
    </div>
	
    <div class="new-form-ui">
        <label class="required"><?php echo $this->form->emprole->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->emprole; ?></div>
        <?php if(isset($this->msgarray['emprole'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->emprole->getId(); ?>"><?php echo $this->msgarray['emprole'];?></span>
        <?php }?>
      </div>
      
      <div class="new-form-ui">
        <label class="required"><?php echo $this->form->emailaddress->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->emailaddress; ?></div>
        <?php if(isset($this->msgarray['emailaddress'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->emailaddress->getId(); ?>"><?php echo $this->msgarray['emailaddress'];?></span>
        <?php }?>
    </div>
    <div class="new-form-ui">
        <label class="required"><?php echo $this->form->jobtitle_id->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->jobtitle_id; ?>
                <?php if(isset($this->msgarray['jobtitle_id'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->jobtitle_id->getId(); ?>"><?php echo $this->msgarray['jobtitle_id'];?></span>
        <?php }?>      
        </div>
    </div>
    <div class="new-form-ui">
        <label class="required"><?php echo $this->form->position_id->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->position_id; ?>
                <?php if(isset($this->msgarray['position_id'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->position_id->getId(); ?>"><?php echo $this->msgarray['position_id'];?></span>
        <?php }?>
        
        </div>
    </div>
    <div class="new-form-ui">
        <label class="required"><?php echo $this->form->date_of_joining_head->getLabel(); ;?> </label>
        <div class="division"><?php echo $this->form->date_of_joining_head; ?></div>
        <?php if(isset($this->msgarray['date_of_joining_head'])){?>
                 <span class="errors" id="errors-<?php echo $this->form->date_of_joining_head->getId(); ?>"><?php echo $this->msgarray['date_of_joining_head'];?></span>
        <?php }?>
    </div>

	<div class="new-form-ui textareaheight">
	  <label>Management Description </label>
	<div class="division"><?php echo $this->form->description; ?></div>
	  <?php if(isset($this->msgarray['description'])){?>
		   <span class="errors" id="errors-<?php echo $this->form->description->getId(); ?>"><?php echo $this->msgarray['description'];?></span>
	  <?php }?>
	</div>
		
<!-- end of organisation head details -->		
        
        
        
        
        
        <div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="closeiframepopup('organisationinfo','cancel');" type="button" >Cancel</button>
		</div>
</form>
</div>
<div id="countriesContainer"  style="display: none; overflow: auto;">
		<div class="heading">
			<a href="javascript:void(0)">
			<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
				border="0" hspace="3" vspace="5" class="closeAttachPopup"
				style="margin: -24px 8px 0 0;"> </a>
		</div>

			<iframe id="countriesCont" class="business_units_iframe" frameborder="0"></iframe>

	</div>
<div id="prefixContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="prefixCont" class="business_units_iframe" frameborder="0"></iframe>
</div>

<div id="employmentstatusContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="employmentstatusCont" class="business_units_iframe" frameborder="0"></iframe>
</div>

<div id="jobtitlesContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="jobtitlesCont" class="business_units_iframe" frameborder="0"></iframe>
</div>

<div id="positionsContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="positionsCont" class="business_units_iframe" frameborder="0"></iframe>
</div>

<div id="statesContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="statesCont" class="business_units_iframe" frameborder="0"></iframe>
</div>  

<div id="citiesContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
	    <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
	</div>

	<iframe id="citiesCont" class="business_units_iframe" frameborder="0"></iframe>
</div>  
<div id="identitycodesContainer"  style="display: none; overflow: auto;">
    <div class="heading">
        <a href="javascript:void(0)">
            <img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> 
        </a>
    </div>
    <iframe id="identitycodesCont" name="identitycodesCont" class="business_units_iframe" frameborder="0"></iframe>
</div>  
<div id="organisationinfoContainer"  style="display: none; overflow: auto;">
	<div class="heading">
		<a href="javascript:void(0)">
		<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
			border="0" hspace="3" vspace="5" class="closeAttachPopup"
			style="margin: -24px 8px 0 0;"> </a>
	</div>

		<iframe id="organisationinfoCont" class="business_units_iframe" frameborder="0"></iframe>

</div>      
<?php } ?>
<script type="text/javascript">
    $(document).ready(function(){
      
        var yearrange = <?php echo "'".date("Y", strtotime("-30 years")).':'.date('Y')."'"; ?>;
		$('#date_of_joining_head').datepicker({
				showOn:'both',
				maxDate: new Date, 
				yearRange: yearrange,
				dateFormat: '<?php echo DATEFORMAT_JS;?>',
				buttonImage: "<?php echo $this->baseUrl("public/media/images/cal.jpg");?>",
				buttonImageOnly: true,
				buttonText: "",
				changeMonth: true,
				changeYear: true, 
                showButtonPanel: true ,
				onClose:function(){
                            from_to_date_validation_org('org_startdate','date_of_joining_head',this,'Date of joining should be greater than organization started on.');
					$('#date_of_joining_head').trigger('blur');
                    }
		});
	});//end of ready function			
</script>
<script type="text/javascript">
			var btnUpload = $('#org_image');
			new AjaxUpload(btnUpload, {	
				action :  base_url+'/organisationinfo/uploadpreview',
				name   : 'profile_photo',  //we can rename it 
				dataType: 'json',
				onSubmit: function(file,ext){		
				if($("#errors-org_image_value").is(":visible"))
				  $("#errors-org_image_value").hide();	
				  $("#orgloaderimg").show();												 
				},
				onComplete: function(file, response){				
					var result = JSON.parse(response);
					if(result.result == 'success')
					{						
						$('#errors-org_image_value').html('');
						$('#imgerr').val(result.result);						
						$("#imgerrmsg").val(result.msg);	
						$("#errors-org_image_value").css('display','block');
						$("#org_image_value").val(result.img);
						$('.org-img').html('<img src="'+base_url+'/public/uploads/preview/'+result.img+'" /><div id="org_image" class="caption uploadbut-org" style="top: -35px; display: none;">Upload Logo</div>');
						$("#orgloaderimg").hide();						
							
	
					}
					else
					{
						$('.uploaderror').show();
						$("#errors-org_image_value").css('display','block');
						$('#errors-org_image_value').html(result.msg);
						$('#imgerr').val(result.result);
						$("#imgerrmsg").val(result.msg);
						$("#orgloaderimg").hide();
						setTimeout(function()
						{
						$('.uploaderror').fadeOut('slow');
						},3000);

					}
					
					
				}

				
			},'json');
	
			var domains = '<?php echo $this->domainValue;?>';
			var errorMsg = "<?php if(isset($this->msgarray['domain'])) echo $this->msgarray['domain'];?>";
			var domainsArr = domains.split(",");
			var domainData = document.getElementById('domain');
			for(var j = 0 ; j <= domainsArr.length ; j++)
			{	
				for(var i = 0 ; i <= domainData.length ; i++)
				{
					if(domainData.options[i] !== undefined)
					{
						if(domainData.options[i].value === domainsArr[j]) 
						{
							if(errorMsg != '' && errorMsg != 'undefined')
							domainData.options[i].selected = false;
							else domainData.options[i].selected = true;
							break;
						}
					}
				}
			}
			
		
		</script>
		
		
<script language='javascript'>
	<?php if($this->popup != '') { ?>
			setTimeout(function(){				
				 closeiframepopup('<?php echo $this->controllername; ?>',''); 
			},2000);
	<?php } ?>
</script>
