<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php
}else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<div class="new-form-ui">
			  <label>Geography Code</label>
			<div class="division"><?php echo $this->form->geographycode; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Default Geography Group</label>
			<div class="division"><?php echo $this->form->defaultGeographyGroup; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Geography Group</label>
			<div class="division"><?php echo $this->form->geographygroupname; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Geography Region</label>
			<div class="division"><?php echo $this->form->geographyregion; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Currency</label>
			<div class="division"><?php echo $this->form->currency; ?></div>
			</div>
			<div class="new-form-ui">
			  <label>Geography City</label>
			<div class="division"><?php echo $this->form->geographycityname; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo $this->baseUrl();?>/geographygroup';" type="button" >Cancel</button>
		</div>
</div>   

<?php }?>    