<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
		if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php 
}else
{
sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
		<?php echo $this->form->businessunit_id; ?>
		<?php echo $this->form->department_id; ?>
		<?php echo $this->form->user_id; ?>
        <div class="total-form-controller view-form-detail">
			
			<div class="new-form-ui">
			  <label >Business Unit</label>
			<div class="division">
				<input type="text" disabled value="<?php echo $this->empdetails['businessunit_name'];?>">
			</div>			
			</div>
			
			<div class="new-form-ui">
			  <label >Department</label>
				<div class="division">
					<input type="text" disabled value="<?php echo $this->empdetails['department_name'];?>">
				</div>			
			</div>
			
			<div class="new-form-ui">
			  <label >Employee</label>
				<div class="division">
					<input type="text" disabled value="<?php echo $this->empdetails['userfullname'];?>">
				</div>			
			</div>
			
			<div class="new-form-ui">
			  <label ><?php echo $this->form->leave_limit->getLabel();?></label>
			<div class="division"><?php echo $this->form->leave_limit; ?></div>
			</div>
				
			<div class="new-form-ui clearall">
			  <label ><?php echo $this->form->alloted_year->getLabel();?></label>
			<div class="division"><?php echo $this->form->alloted_year; ?></div>
			</div>
			
		<div class="new-form-ui-submit">		
			<?php if(($this->editpermission == 'Yes')) { ?>
					 <input type="button" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
					<button onclick="window.location.href='<?php echo BASE_URL; ?>leavemanagement';" id="Cancel" name="Cancel" type="button" >Cancel</button>
		   <?php }
		   else{
			?>
					<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>addemployeeleaves';" type="button"  value="Back"  />
    	    <?php } ?>							
		</div>
</div>
</form>
<?php } ?>