<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->data)){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
				Employee deleted
				<?php }?>
	</div>

<?php 
}
else
{
	if(!empty($this->employeedata))
	 {
		echo $this->employeedetails($this->employeedata,'myemployees',$this->id); 
	 } 
?>
<div class="right-block-data right-over-border"> 
	<div id="error_message" style="display:none;"></div>
	
            <input type="hidden" name="tmp_emp_name" id="tmp_emp_name" />
		<?php echo $this->form->id; ?><?php echo $this->form->user_id; ?>
			<div class="total-form-controller view-form-detail">
			<div class="new-form-ui">
				<label><?php echo $this->form->employeeId->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->employeeId; ?>
					<span id="errors-<?php echo $this->form->employeeId->getId(); ?>" class="errors"><?php echo isset($this->msgarray['employeeId'])?$this->msgarray['employeeId']:"";?></span>
				</div>
			</div>
            <div class="new-form-ui">
				<label><?php echo $this->form->prefix_id->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->prefix_id; ?></div>
			</div> 
			<!--  				
            <div class="new-form-ui" id="iddiv_fullname" style="display:none;">
				<label><?php //echo $this->form->userfullname->getLabel(); ?></label>
				<div class="division"><input type="text" disabled value="<?php //echo $this->form->userfullname->getValue(); ?>" /></div>
                <span id="errors-<?php //echo $this->form->userfullname->getId(); ?>" class="errors"><?php //echo isset($this->msgarray['userfullname'])?$this->msgarray['userfullname']:"";?></span>
            </div>  
            -->
            <div id="iddiv_fullname" style="display:none;">     
                            <div class="new-form-ui" >
                                <label><?php echo $this->form->firstname->getLabel(); ?></label>
                                <div class="division">
									<?php echo $this->form->firstname; ?>
								</div>
                                <span id="errors-<?php echo $this->form->firstname->getId(); ?>" class="errors"><?php echo isset($this->msgarray['firstname'])?$this->msgarray['firstname']:"";?></span>
	                            </div>
                            
                            
	                            <div class="new-form-ui" >
	                                <label><?php echo $this->form->lastname->getLabel(); ?></label>
                                <div class="division">
									<?php echo $this->form->lastname; ?>
								</div>
                                <span id="errors-<?php echo $this->form->lastname->getId(); ?>" class="errors"><?php echo isset($this->msgarray['lastname'])?$this->msgarray['lastname']:"";?></span>
                            </div>  
            </div>              
			
			<div class="new-form-ui" id="iddiv_referredby" style="display:none;">
				<label><?php echo $this->form->candidatereferredby->getLabel(); ?></label>
				<div class="division">
					<select disabled>
					<option><?php echo $this->form->candidatereferredby->getValue(); ?></option>
					</select>
				</div>
				<span id="errors-<?php echo $this->form->candidatereferredby->getId(); ?>" class="errors"><?php echo isset($this->msgarray['candidatereferredby'])?$this->msgarray['candidatereferredby']:"";?></span>
			</div>
			
			<div class="new-form-ui" id="iddiv_canditatename">
				<label><?php echo $this->form->rccandidatename->getLabel(); ?></label>
				<div class="division">
					<select disabled>
						<option><?php echo $this->form->rccandidatename->getValue(); ?></option>
					</select>
				  <span id="errors-<?php echo $this->form->rccandidatename->getId(); ?>" class="errors"><?php echo isset($this->msgarray['rccandidatename'])?$this->msgarray['rccandidatename']:"";?></span>                    
				</div>
			</div>
			
			<div class="new-form-ui">
				<label><?php echo $this->form->modeofentry->getLabel(); ?></label>
				<div class="division">
					<select disabled>
					<option><?php echo $this->form->modeofentry->getValue(); ?></option>
					</select>
				 <span id="errors-<?php echo $this->form->modeofentry->getId(); ?>" class="errors"><?php echo isset($this->msgarray['modeofentry'])?$this->msgarray['modeofentry']:"";?></span>
				</div>
			</div>
			
			<div class="new-form-ui" id="iddiv_otherentry" style="display:none">
				<label><?php echo $this->form->other_modeofentry->getLabel(); ?></label>
				<div class="division">
					<input type="text" disabled value="<?php echo $this->form->other_modeofentry->getValue(); ?>" />
				  <span id="errors-<?php echo $this->form->other_modeofentry->getId(); ?>" class="errors"><?php echo isset($this->msgarray['other_modeofentry'])?$this->msgarray['other_modeofentry']:"";?></span>
				</div>
			</div>
							
			<div class="new-form-ui" id="iddivrequi" style="display:none;">
				<label>Requisition code</label>
				<div class="division"><?php 
				if(isset($data['requisition_code']))
					$this->form->disp_requi->setValue($data['requisition_code']);
				echo $this->form->disp_requi; ?></div>
            </div>
			
			<div class="new-form-ui">
				<label><?php echo $this->form->emprole->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->emprole; ?>
				<span id="errors-<?php echo $this->form->emprole->getId(); ?>" class="errors"><?php echo isset($this->msgarray['emprole'])?$this->msgarray['emprole']:"";?></span>
				</div>
			</div>
                            
			<div class="new-form-ui">
				<label><?php echo $this->form->emailaddress->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->emailaddress; ?></div>
				<span class="errors" id="errors-<?php echo $this->form->emailaddress->getId(); ?>"><?php echo isset($this->msgarray['emailaddress'])?$this->msgarray['emailaddress']:"";?></span>
			</div>
											
			<div class="new-form-ui">
			  <label>Business Unit</label>
			<div class="division"><?php echo $this->form->businessunit_id; ?></div>
			<?php if(isset($this->msgarray['businessunit_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->businessunit_id->getId(); ?>"><?php echo $this->msgarray['businessunit_id'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Department<!-- <img class="tooltip" title="Select business unit to populate departments" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png">--></label>
			<div class="division"><?php echo $this->form->department_id; ?></div>
			<!--<div id="helptext" class="helptext">Select business unit to populate departments</div>-->
			<span class="errors" id="errors-<?php echo $this->form->department_id->getId(); ?>" style="display:none;"></span>
			<?php if(isset($this->msgarray['department_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->department_id->getId(); ?>"><?php echo $this->msgarray['department_id'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Reporting Manager</label>
			<div class="division"><?php echo $this->form->reporting_manager; ?></div>
			<span class="errors" id="errors-<?php echo $this->form->reporting_manager->getId(); ?>" style="display:none;"></span>
			<?php if(isset($this->msgarray['reporting_manager'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->reporting_manager->getId(); ?>"><?php echo $this->msgarray['reporting_manager'];?></span>
			<?php }?>
			</div>
												
			<div class="new-form-ui">
			  <label>Job Title</label>
			<div class="division"><?php echo $this->form->jobtitle_id; ?></div>
			<?php if(isset($this->msgarray['jobtitle_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->jobtitle_id->getId(); ?>"><?php echo $this->msgarray['jobtitle_id'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Position<!-- <img class="tooltip" title="Select job title to populate positions" src="<?php echo MEDIA_PATH;?>images/help.png">--></label>
			<div class="division"><?php echo $this->form->position_id; ?></div>
			<!--<div id="helptext" class="helptext">Select job title to populate positions</div>-->
			<span class="errors" id="positionerror" style="display:none;"></span>
			<?php if(isset($this->msgarray['position_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->position_id->getId(); ?>"><?php echo $this->msgarray['position_id'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Employment Status</label>
			<div class="division"><?php echo $this->form->emp_status_id; ?></div>
			<?php if(isset($this->msgarray['emp_status_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->emp_status_id->getId(); ?>"><?php echo $this->msgarray['emp_status_id'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Date of joining<!-- <img class="tooltip" title="mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png">--></label>
			<div class="division"><?php echo $this->form->date_of_joining; ?></div>
			<?php if(isset($this->msgarray['date_of_joining'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->date_of_joining->getId(); ?>"><?php echo $this->msgarray['date_of_joining'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Date of leaving <!--<img class="tooltip" title="mm-dd-yyyy" src="<?php //echo $this->baseUrl().'/public/media/';?>images/help.png">--></label>
			<div class="division"><?php echo $this->form->date_of_leaving; ?></div>
			<span class="errors" id="errors-date_of_leaving" style="display:none;"></span>
			<?php if(isset($this->msgarray['date_of_leaving'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->date_of_leaving->getId(); ?>"><?php echo $this->msgarray['date_of_leaving'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label>Years of Experience</label>
			<div class="division"><?php echo $this->form->years_exp; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label ><?php echo $this->form->extension_number->getLabel(); ?></label>
			<div class="division"><?php echo $this->form->extension_number; ?></div>
			<?php if(isset($this->msgarray['extension_number'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->extension_number->getId(); ?>"><?php echo $this->msgarray['extension_number'];?></span>
			<?php }?>
			</div>
				
			<div class="new-form-ui">
			  <label ><?php echo $this->form->office_number->getLabel(); ?></label>
			<div class="division"><?php echo $this->form->office_number; ?></div>
			<?php if(isset($this->msgarray['office_number'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->office_number->getId(); ?>"><?php echo $this->msgarray['office_number'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label ><?php echo $this->form->office_faxnumber->getLabel(); ?></label>
			<div class="division"><?php echo $this->form->office_faxnumber; ?></div>
			<?php if(isset($this->msgarray['office_faxnumber'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->office_faxnumber->getId(); ?>"><?php echo $this->msgarray['office_faxnumber'];?></span>
			<?php }?>
			</div>
			 
	</div>
     
</div>	
</div>
<script type='text/javascript'>
$(document).ready(function(){

   $("#empdetails").addClass('active');
    $("#empdetails").removeAttr("onclick");
    
 
<?php 
    if($this->form->id->getValue() != '')
    {
?>     
     
        var val = '<?php echo $this->form->modeofentry->getValue();?>';
        if(val == 'Direct')
        {
            $('#iddiv_fullname').show();
            $('#rccandidatename').val('');
            $('#iddiv_canditatename').hide();            
        }
        else if(val == 'Reference')
        {
            $('#iddiv_referredby').show();
            $('#iddiv_fullname').hide();
            //$('#userfullname').val('');
            $('#firstname').val('');
            $('#lastname').val('');
            $('#iddiv_canditatename').show();        
        }
        else if(val == 'Other')
        {
            $('#iddiv_canditatename').show();            
            $('#iddiv_otherentry').show();    
            $('#candidatereferredby').val('');                        
            //$('#userfullname').val('');
            $('#firstname').val('');
            $('#lastname').val('');
            $('#iddiv_referredby').hide();
            $('#iddiv_fullname').hide();            
        }
        else 
        {
            $('#iddiv_canditatename').show();
            $('#candidatereferredby').val('');
            //$('#userfullname').val('');
            $('#firstname').val('');
            $('#lastname').val('');
            $('#iddiv_referredby').hide();
            $('#iddiv_fullname').hide();           
        }
        
<?php         
    }
?>
});//end of ready function
</script>
<?php } ?>