<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
//echo $this->message;
?>

<div class="total-form-controller">
<div class="separetor-heading">Requisition Details <div class="add-more-form-1">+ Add Candidates</div></div>

	<div class="new-form-ui">
            <label class="required">Requisition ID</label>
             <div class="division"><select></select></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Created Date</label>
            <div class="division"><span class="textarea-data-show">19-09-2013</span></div>
    </div>

    <div class="new-form-ui">
            <label class="required">Created By</label>
            <div class="division"><span class="textarea-data-show">Pavan Somepalli</span></div>
    </div>

    <div class="new-form-ui">
            <label class="required">Due Date <img class="tooltip" title="format- mm-dd-yy" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
            <div class="division"><span class="textarea-data-show">26-09-2013</span></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Business Unit</label>
            <div class="division"><span class="textarea-data-show">Software Unit</span></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Department</label>
            <div class="division"><span class="textarea-data-show">Development</span></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Position name</label>
            <div class="division"><span class="textarea-data-show">PHP Developer</span></div>
    </div>
       <div class="new-form-ui">
            <label class="required">Reporting Manager</label>
              <div class="division"><span class="textarea-data-show">Pavan Somepalli</span></div>
    </div>
    	<div class="new-form-ui">
            <label class="required">Applcation Status</label>
             <div class="division"><select></select></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Job Title</label>
            <div class="division"><span class="textarea-data-show">Jr. Software Engg.</span></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Requried no. of Positions</label>
            <div class="division"><span class="textarea-data-show">3</span></div>
    </div>
     <div class="new-form-ui textareaheight">
            <label>Job Description</label>
          <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
      </div>
        <div class="new-form-ui textareaheight">
            <label>Required Skills</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
        </div>
  	<div class="new-form-ui">
            <label class="required">Required Qualification</label>
            <div class="division"><span class="textarea-data-show">B.E/ B.Tech/ M.Tech</span></div>
    </div>
  	<div class="new-form-ui">
            <label class="required">Required Experience Range</label>
            <div class="division"><span class="textarea-data-show">3-5 years</span></div>
    </div>

  	<div class="new-form-ui">
            <label class="required">Employment Type</label>
            <div class="division"><span class="textarea-data-show">Full Time</span></div>
    </div>
  	<div class="new-form-ui">
            <label class="required">Priority</label>
            <div class="division"><span class="textarea-data-show">High</span></div>
    </div>
   <div class="new-form-ui textareaheight">
            <label class="required">Additional Information</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
    </div>
 
<div class="new-form-ui-submit">
		<input type="submit" value="save" />
		<button type="button" id="Cancel" name="Cancel">Cancel</button>
</div>  
    
    
    
</div>    