
<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>				
<span style='color:#3b3b3b;'>Hi,</span><br />
<div style='padding:20px 0 0 0;color:#3b3b3b;'><?php echo $this->mail_content?></div>
<div style='padding:20px 0 10px 0;'>Please <a href="<?php echo BASE_URL?>" target='_blank' style='color:#b3512f;'>click here</a> to login  to your <b><?php echo APPLICATION_NAME?></b> account to check the details.</div>
</div> 



	  

	  
