<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
        <div class="total-form-controller view-form-detail">
		 	<div class="new-form-ui ">
			  <label id="injuredDate">Leave limit</label>
				<div class="division loca_state_div">
				<?php //echo $this->form->emp_leave_limit; ?>
				<?php echo $this->form->leave_limit; ?>
				</div>
			</div>
			<div class="new-form-ui ">
			<label >Used leaves</label>
			<div class="division"><?php echo $this->form->used_leaves; ?></div>
			</div>
			
			<div class="new-form-ui">
				  <label>Year</label>
			<div class="division"><?php echo $this->form->alloted_year; ?></div>
			</div>

        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empleaves','cancel');" type="button" value="Close"  />
        <!-- <button onclick="closeiframepopup('empleaves','cancel');" type="button">Cancel</button>-->
        </div>		

</div>