<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php $baseUrl = $this->serverUrl().$this->baseUrl();
?>
<div id="error_message" style="display:none;"></div>
<div class="poc-ui-data-control">

		<?php echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
		
		    <div class="new-form-ui">
			 <label id="injuredDate"><?php echo $this->form->educationlevel->getLabel(); ?></label>
				<div class="division loca_state_div"><?php echo $this->form->educationlevel; ?></div>
			</div>
			
		 	<div class="new-form-ui">
			  <label id="injuredDate">Institution Name</label>
				<div class="division loca_state_div"><?php echo $this->form->institution_name; ?></div>
			</div>
			
			<div class="new-form-ui ">
				<label>Course</label>
				<div class="division"><?php echo $this->form->course; ?></div>
			</div>
			
			<div class="new-form-ui ">
			    <label>From  </label>
				<div class="division"><?php echo $this->form->from_date; ?></div>
			</div>
															
			<div class="new-form-ui ">
			  <label>To  </label>
			  <div class="division"><?php echo $this->form->to_date; ?></div>
			</div>
				
			<div class="new-form-ui ">
			  <label>Percentage</label>
			  <div class="division"><?php echo $this->form->percentage; ?></div>
			</div>


        <div class="new-form-ui-submit" id="formSubmit">
        <input onclick="closeiframepopup('educationdetails','cancel');" type="button" value="close"  />
        </div>
</div>      
</form>

