<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$cdata = $this->cdata;
$workdata = $this->workdata;
$candidate_details_view_helper = $this->candidatedetails(); 
?>
<?php 

if($this->ermsg == '')  { ?>
<div class="requisitions-block">
<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
    <?php
    if($this->previ_data == 'Yes')
    {
    ?>
    <div class="edit-btn">
        <div class="new-form-ui-submit ">
            <input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />        
        </div>
    </div>
    <?php 
    }
    ?>
<div class="separetor-heading">Candidate Details</div>

<table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table">

<tr class="req-bg-form">
<td width="20%">Requisition ID <b>:</b></td>
<td width="30%"><?php echo $cdata['requisition_code']." - ".$cdata['jobtitle_name'];?></td>
<td width="20%">Status <b>:</b></td>
<td width="30%"><?php echo $cdata['cand_status'];?></td>
</tr>

<tr  class="req-no-form">
<td>Candidate first name <b>:</b></td>
<td><?php echo $cdata['candidate_firstname'];?></td>
<td>Candidate last name <b>:</b></td>
<td><?php echo $cdata['candidate_lastname'];?></td>
</tr>

<tr class="req-bg-form">
<td>Email <b>:</b></td>
<td><?php echo $cdata['emailid'];?></td>
<td>Contact number <b>:</b></td>
<td><?php echo $cdata['contact_number'];?></td>
</tr>

<tr class="req-no-form">
<td>Qualification <b>:</b></td>
<td><?php echo $cdata['qualification'];?></td>
<td>Work experience <b>:</b></td>
<td><?php echo $cdata['experience'];?></td>
</tr>

<tr class="req-bg-form">
<td>Skill set <b>:</b></td>
<td><?php  echo $cdata['skillset'];?></td>
<td>Education summary <b>:</b></td>
<td><?php echo $cdata['education_summary'];?></td>
</tr>

<tr class="req-no-form">
<td valign="top">Summary <b>:</b></td>
<td><?php echo $cdata['summary'];?></td>
<td>Location <b>:</b></td>
<td><?php echo $cdata['cand_location'];?> </td>
</tr>

<tr class="req-bg-form">
<td>Country <b>:</b></td>
<td><?php echo $cdata['country_name'];?></td>
<td>State <b>:</b></td>
<td><?php echo $cdata['state_name'];?></td>
</tr>
<tr class="req-no-form">
<td>City <b>:</b></td>
<td><?php echo $cdata['city_name'];?></td>
<td>Postal code <b>:</b></td>
<td><?php echo $cdata['pincode'];?></td>
</tr>

<tr class="req-bg-form">
<td>Resume <b>:</b></td>
<td><?php $candidate_details_view_helper->loadResumeName($cdata); ?></td>
<td></td>
<td></td>
</tr>

</table>
    
<?php 
if(!empty($workdata))
{
?>
<div class="separetor-heading mrgetop10">Previous Company Details</div>
        
        <div class="company-new-div">
        	<div class="company-tabs">
            	<h1>Company 1</h1>
                <table cellspacing="0" cellpadding="0" width="100%" border="0" class="requisition-table">
                    <tr class="req-bg-form">
                        <td width="50%">Company Name <b>:</b></td>
                        <td width="50%"><?php echo isset($workdata[0]['company_name'])?$workdata[0]['company_name']:"-";?></td>
	                </tr>
                    <tr class="req-no-form">
                        <td>Designation <b>:</b></td>
                        <td><?php echo isset($workdata[0]['cand_designation'])?$workdata[0]['cand_designation']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form">
                        <td>From <b>:</b></td>
                        <td><?php echo isset($workdata[0]['cand_fromdate'])?$workdata[0]['cand_fromdate']:"-";?></td>
                    </tr>
                    <tr class="req-no-form">
                        <td>To <b>:</b></td>
                        <td><?php echo isset($workdata[0]['cand_todate'])?$workdata[0]['cand_todate']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form">
                        <td>Contact Number <b>:</b></td>
                        <td><?php echo isset($workdata[0]['contact_number'])?$workdata[0]['contact_number']:"-";?></td>
                    </tr>
                    <tr class="req-no-form">
                        <td>Web site <b>:</b></td>
                        <td><?php echo isset($workdata[0]['company_website'])?$workdata[0]['company_website']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form no-border">
                        <td>Address <b>:</b></td>
                        <td><?php echo isset($workdata[0]['company_address'])?$workdata[0]['company_address']:"-";?></td>
                    </tr>
                 </table>
            
            </div>
            <div class="company-tabs">
            	<h1>Company 2</h1>
                <table cellspacing="0" cellpadding="0" width="100%" border="0" class="requisition-table">
                    <tr class="req-bg-form">
                        <td width="50%">Company Name <b>:</b></td>
                        <td width="50%"><?php echo isset($workdata[1]['company_name'])?$workdata[1]['company_name']:"-";?></td>
	                </tr>
                    <tr class="req-no-form">
                        <td>Designation <b>:</b></td>
                        <td><?php echo isset($workdata[1]['cand_designation'])?$workdata[1]['cand_designation']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form">
                        <td>From <b>:</b></td>
                        <td><?php echo isset($workdata[1]['cand_fromdate'])?$workdata[1]['cand_fromdate']:"-";?></td>
                    </tr>
                    <tr class="req-no-form">
                        <td>To <b>:</b></td>
                        <td><?php echo isset($workdata[1]['cand_todate'])?$workdata[1]['cand_todate']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form">
                        <td>Contact Number <b>:</b></td>
                        <td><?php echo isset($workdata[1]['contact_number'])?$workdata[1]['contact_number']:"-";?></td>
                    </tr>
                    <tr class="req-no-form">
                        <td>Web site <b>:</b></td>
                        <td><?php echo isset($workdata[1]['company_website'])?$workdata[1]['company_website']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form no-border">
                        <td>Address <b>:</b></td>
                        <td><?php echo isset($workdata[1]['company_address'])?$workdata[1]['company_address']:"-";?></td>
                    </tr>
                 </table>
            
            </div>
            <div class="company-tabs">
            	<h1>Company 3</h1>
                <table cellspacing="0" cellpadding="0" width="100%" border="0" class="requisition-table">
                    <tr class="req-bg-form">
                        <td width="50%">Company Name <b>:</b></td>
                        <td width="50%"><?php echo isset($workdata[2]['company_name'])?$workdata[2]['company_name']:"-";?></td>
	                </tr>
                    <tr class="req-no-form">
                        <td>Designation <b>:</b></td>
                        <td><?php echo isset($workdata[2]['cand_designation'])?$workdata[2]['cand_designation']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form">
                        <td>From <b>:</b></td>
                        <td><?php echo isset($workdata[2]['cand_fromdate'])?$workdata[2]['cand_fromdate']:"-";?></td>
                    </tr>
                    <tr class="req-no-form">
                        <td>To <b>:</b></td>
                        <td><?php echo isset($workdata[2]['cand_todate'])?$workdata[2]['cand_todate']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form">
                        <td>Contact Number <b>:</b></td>
                        <td><?php echo isset($workdata[2]['contact_number'])?$workdata[2]['contact_number']:"-";?></td>
                    </tr>
                    <tr class="req-no-form">
                        <td>Web site <b>:</b></td>
                        <td><?php echo isset($workdata[2]['company_website'])?$workdata[2]['company_website']:"-";?></td>
                    </tr>
                    <tr class="req-bg-form no-border">
                        <td>Address <b>:</b></td>
                        <td><?php echo isset($workdata[2]['company_address'])?$workdata[2]['company_address']:"-";?></td>
                    </tr>
                 </table>
            
            </div>
        
       <?php 
}
       ?>
        </div>
   
</div>
</div>
<script type='text/javascript'>
$(document).ready(function(){
	/* Making window responsive*/
 	var complete_width = $('.form-ui-full').width();
	$('.form-ui-full label').css("width", "160");
	$('.form-ui-full .division').css("width", (complete_width-(190)));	
		
	 function checkWidth() {
        var complete_width = $('.form-ui-full').width();		
		$('.form-ui-full label').css("width", "160");
		$('.form-ui-full .division').css("width", (complete_width-(190)));		
    }
	$(window).resize(function() {
		checkWidth();
	}); 
});
</script>
<?php } else { ?>No data found.<?php } ?>

<?php 
}
?>