<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/

if($this->ermsg == '')  
{
?>
    <div class="requisitions-block  feedforwardinit_view">
        <div class="cofig_title" style="margin-left: 0px;padding-top: 0px;">Initialization Details
                <div class="new-form-ui-submit "  style="margin-top: 0px; float: right; width: auto; margin-left: 0px; ">
				<div class="back-to-page" style="position: relative; float: right; top: 0px;">
                    <input type="button" class="fltright" onclick="window.location.href='<?php echo $this->baseUrl();?>/feedforwardinit';" value="Back" />
					</div>
                    <?php if($this->data['status'] == 1){?>
                    	<input type="button" class="flt	right" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
                    <?php }?>        
                </div>
            </div>

        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table view-table-data">
            <tr class="req-bg-form">
                <td width="20%"><span class="head_txt">Business Unit</span>  </td>
                <td width="30%"><?php echo $this->data['unitname'];?></td>
                <td width="20%"><span class="head_txt">Department </span> </td>
                <td width="30%"><?php echo $this->data['deptname']!=''?$this->data['deptname']:"--";?></td>
            </tr>
            <tr  class="req-no-form">
                <td><span class="head_txt">Mode </span> </td>
                <td><?php echo $this->data['ff_mode'];?></td>
                <td><span class="head_txt">From Year </span> </td>
                <td><?php echo $this->data['ff_from_year'];?></td>
            </tr>
            <tr class="req-bg-form">
                <td><span class="head_txt">To Year</span>  </td>
                <td><?php echo $this->data['ff_to_year'];?></td>
                <td><span class="head_txt">Period </span> </td>
                <td><?php 
                if($this->data['ff_mode'] == 'Quarterly')
                    echo "Q".$this->data['ff_period'];
                else if($this->data['ff_mode'] == 'Half-yearly')
                    echo "H".$this->data['ff_period'];
                else echo "Yearly";
                ?></td>
            </tr>
            <tr class="req-no-form">
                <td><span class="head_txt">Enabled To  </span></td>
                <td><?php echo $this->data['enable_to'] == 1?"All Employees":"Appraisal Employees";?></td>
                <td><span class="head_txt">Due Date </span> </td>
                <td><?php echo sapp_Global::change_date($this->data['ff_due_date'],'view');?></td>
            </tr>
            <?php if($this->data['initialize_status'] == 1) { ?>
	            <tr class="req-bg-form">
	                <td><span class="head_txt">Initialized To </span></td>
	                <td><?php echo $this->empsCount['total'].' Employees';?></td>
	                <td><span class="head_txt">Completed </span> </td>
	                <td><?php echo $this->empsCount['completed'].' Employees';?></td>
	            </tr>
            <?php } ?>
            
            <tr class="req-<?php echo $this->data['initialize_status'] == 1?'no':'bg';?>-form">
                <td><span class="head_txt">Employee Details </span> </td>
                <td><?php echo $this->data['employee_name_view'] == 1?"Show":"Hide";?></td>
                <td><span class="head_txt">Process Status </span> </td>
                <td><?php echo $this->data['ff_process_status'];?></td>
            </tr>
            <tr class="req-<?php echo $this->data['initialize_status'] == 1?'bg':'no';?>-form">
            	<td><span class="head_txt">Status </span> </td>
                <td><?php echo $this->data['status'] == 1?"Open":"Close";?></td>
                <td colspan="2"></td>
            </tr>
        </table>
        
        <?php echo sapp_PerformanceHelper::ff_questions_privileges_view($this->getQuestions, $this->check_array);?>
        
    </div>

<?php }
else
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php     
}
?>
<div class="clear"></div>
</div><!-- end of steps -->