<?php
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>
<?php 

if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$data = $this->data;
$id = $this->id;
$previ_data = $this->previ_data;

?>
<script type="text/javascript" src="<?php echo MEDIA_PATH;?>js/jquery.prettyPhoto.js"></script>
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/prettyPhoto.css" />
<?php 
if($this->ermsg == '')  { ?>
<div class="requisitions-block">
<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
   
   <div class="cofig_title" style="margin-left: 0px; padding-top: 0px;">Announcements 
   <?php
		$auth = Zend_Auth::getInstance();
     	if($auth->hasIdentity()){
			$loginuserRole = $auth->getStorage()->read()->emprole;
		}
    if(($previ_data == 'Yes' && $data['status']==1) || $loginuserRole == SUPERADMINROLE)
    {
    ?>
	    
	        <div class="new-form-ui-submit "  style="float: right; width: auto;">
	            <input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />        
	        </div>
	   
    <?php 
    }
    ?>
	</div>
   
 <table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table view-table-data">

		<tr class="req-bg-form">
		<td width="20%"><span class="head_txt">Business Units </span></td>
		<td width="30%"><?php echo $data['busi_names'];?></td>
		</tr>
		
		<tr class="req-no-form">
		<td width="20%"><span class="head_txt">Departments </span></td>
		<td width="30%"><?php echo $data['dept_names'];?></td>
		</tr>
		
		<tr class="req-bg-form">
		<td width="20%"><span class="head_txt">Title </span></td>
		<td width="30%"><?php echo $data['title'];?></td>
		</tr>
		
		<tr class="req-no-form">
		<td><span class="head_txt">Description </span></td>
		<td class="post_align"><?php echo $data['description'];?></td>
		</tr>
		
		<?php if($data['status']==2){?>
			<tr class="req-bg-form">
			<td><span class="head_txt">Posted Date</span></td>
			<td><?php echo sapp_Global::change_date($data['modifieddate'], 'view');?></td>
			</tr>
		<?php }?>
		
		<?php if($data['attachments']){?>
			<tr class="req-bg-form">
			<td><span class="head_txt">Attachments</span></td>
			<td class="announcements_link">
				<?php if($data['status']==2){ $path = CA_FILES_PATH; } else { $path = CA_FILES_TEMP_PATH; }				
            		$attachments = json_decode($data['attachments'],true); $i=0;
                    foreach ($attachments as $k => $v){
                        if(in_array(strtolower(sapp_Htmlhelper::getExtension($v["new_name"])), array('jpg','png','gif','jpeg'))) {?>
                        <a href="<?php echo $path.$v["new_name"];?>" rel="prettyPhoto[pp_gal]" title="<?php echo $v["original_name"];?>">
                        <?php if($i == 0){ ?>Click to view<?php }?>
                        </a>
                    <?php } else {?>
                        <a href="<?php echo $path.$v["new_name"];?>?iframe=true&width=80%&height=90%" rel="prettyPhoto[pp_gal]" title="<?php echo $v["original_name"];?>">
                        <?php if($i == 0){ ?>Click to view<?php }?>
                        </a>
                <?php }$i++;}?>
			</td>
			</tr>
		<?php }?>
		
   </table>
   </div>
</div>
<script type="text/javascript">
$(document).ready(function(){
	$("a[rel^='prettyPhoto']").prettyPhoto({social_tools : '', deeplinking: false});
});
</script>
<?php } }?>