<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
$options_data = "";
$options_data .= sapp_Global::selectOptionBuilder('', 'Select City');
if(!empty($this->citiesmodeldata))
{
	
	if($this->con == 'city')
	{
		foreach ($this->citiesmodeldata as $city) {
		$options_data .= sapp_Global::selectOptionBuilder($city['city_org_id'].'!@#'.utf8_encode($city['city']),utf8_encode($city['city']));
		}
		echo $options_data;
	}
	else{
		foreach ($this->citiesmodeldata as $city) {
		$options_data .= sapp_Global::selectOptionBuilder($city['id'].'!@#'.utf8_encode($city['city_name']),utf8_encode($city['city_name']));
		}
		if($this->con == 'otheroption')
		{
		  $options_data .= sapp_Global::selectOptionBuilder('other','Other');
		}
		echo $options_data;
	}
}else
{
  echo "nocities";
}
?> 