<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>
<?php 
$baseUrl = $this->serverUrl().$this->baseUrl();
$assetuserlogdata = $this->assetuserlogdata;
//echo "<pre>";print_r($assetuserlogdata);di
?>
<div class="total-form-controller view-form-detail">
		
		<div style="margin-left: 0px; padding-top: 0px; padding-bottom: 20px;  float: none;" class="cofig_title">Asset History
			<div style="margin-top: 0px; float: right; width: auto;" class="new-form-ui-submit ">
				<div style="position: relative; float: right; top: 0px;" class="back-to-page">
					<input type="button" style="margin-right: 0px;" value="Back" name="Back" onclick="window.location.href='<?php echo BASE_URL; ?>assets/assetcategories';">
				</div>
				
			</div>
		 </div>
		
  
      <?php 
		 if(count($this->assetuserlogdata) > 0){
		 	$i = 0;
		 	?>   
        <?php 
		 	foreach($this->assetuserlogdata as $asset_user_log){
    	  ?>
    	
    	  <p><?php echo $asset_user_log['createddate'];?> <?php echo $this->objName?> <b>Allocated To</b> -<?php echo $asset_user_log['userfullname'];?></p><br/>
    	  <p>  ......................................................................................................................................................</p>
         <?php }?> 
		 <?php 
		 $i++;
 		}	
 		?>
         
     
			
	</div>        
      
      
      
     
				
 
