<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if($this->record == 'no data') { ?>
			<div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php }else if($this->ermsg == 'nodata') { ?>
			<div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php } else { ?>
<div class="total-form-controller view-form-detail">
<div id="error_message" style="display:none;"></div>
<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction(); ?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
		<?php echo $this->form->pocid_1; ?>
		<?php echo $this->form->pocid_2; ?>
		<?php echo $this->form->pocid_3; ?>
		<div class="new-form-ui">
		  <label>Agency Name</label>
		<div class="division"><?php echo $this->form->agencyname; ?></div>
		</div>
		
        <div class="new-form-ui">
		  <label>Website URL</label> </label>
		<div class="division"><?php echo $this->form->website_url; ?></div>
		</div>
        
		<div class="new-form-ui">
		  <label>Primary Phone </label>
		<div class="division"><?php echo $this->form->primaryphone; ?></div>
		</div>
		
		<div class="new-form-ui">
		  <label>Secondary Phone </label>
		<div class="division"><?php echo $this->form->secondaryphone; ?></div>		 
		</div>
		
		<div class="new-form-ui-multi">
		  <label>Screening Type </label>
		<div class="division"><?php echo $this->form->bg_checktype; ?></div>
		</div>
        <div class="new-form-ui textareaheight">
		  <label>Address </label>
		<div class="division"><?php echo $this->form->address; ?></div>
		</div>
		
<div class="separetor-heading mrgetop5">POC Details</div>
<div class="poc-ui-data-control">        
 <div class="left-block-ui-data">
    <div class="agency-ui">
        <ul>
            <li class="active" id="poclifirst" style="cursor:pointer;" onclick="contactElements('first');">Contact 1</li>
            <li id="poclisecond" style="cursor:pointer;" onclick="contactElements('second');">Contact 2</li>
            <li id="poclithird" style="cursor:pointer;" onclick="contactElements('third');">Contact 3</li>
        </ul>
	</div>
</div>        
<div class="right-block-data">        		
			<div id="firstpoc" class="clearb fltleft">
				<div class="new-form-ui">
				  <label>First Name</label>
				<div class="division"><?php echo $this->form->firstname_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label>Last Name</label> </label>
				<div class="division"><?php echo $this->form->lastname_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label>Mobile </label>
				<div class="division"><?php echo $this->form->mobile_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label> Email </label>
				<div class="division"><?php echo $this->form->email_1; ?></div>
				</div>						
				<div class="new-form-ui">
				  <label> Location</label>
				<div class="division"><?php echo $this->form->location_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label> Country </label>
				<div class="division"><?php echo $this->form->country_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label> State</label>
				<div class="division"><?php echo $this->form->state_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label> City</label>
				<div class="division"><?php echo $this->form->city_1; ?></div>
				</div>				
				<div class="new-form-ui">
				  <label> Contact type </label>
				<div class="division"><?php echo $this->form->contact_type_1; ?></div>
				</div>
			</div>
		
		<div id="secondpoc" style="display:none;" class="clearb fltleft">
			<?php echo $this->form->secondpocid; ?>
			<div class="new-form-ui">
			  <label>First Name</label>
			<div class="division"><?php echo $this->form->firstname_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label>Last Name</label> </label>
			<div class="division"><?php echo $this->form->lastname_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label>Mobile </label>
			<div class="division"><?php echo $this->form->mobile_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Email </label>
			<div class="division"><?php echo $this->form->email_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Location</label>
			<div class="division"><?php echo $this->form->location_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Country </label>
			<div class="division"><?php echo $this->form->country_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> State</label>
			<div class="division"><?php echo $this->form->state_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> City</label>
			<div class="division"><?php echo $this->form->city_2; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Contact type </label>
			<div class="division"><?php echo $this->form->contact_type_2; ?></div>
			</div>
		</div>			
		<div id="thirdpoc" style="display:none;" class="clearb fltleft">
			<?php echo $this->form->thirdpocid; ?>
			<div class="new-form-ui">
			  <label>First Name</label>
			<div class="division"><?php echo $this->form->firstname_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label>Last Name</label> </label>
			<div class="division"><?php echo $this->form->lastname_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label>Mobile </label>
			<div class="division"><?php echo $this->form->mobile_3; ?></div>
			  <?php if(isset($this->msgarray['mobile_3'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->mobile_3->getId(); ?>"><?php echo $this->msgarray['mobile_3'];?></span>
			  <?php }?>			  
			</div>			
			<div class="new-form-ui">
			  <label> Email </label>
			<div class="division"><?php echo $this->form->email_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Location</label>
			<div class="division"><?php echo $this->form->location_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Country </label>
			<div class="division"><?php echo $this->form->country_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> State</label>
			<div class="division"><?php echo $this->form->state_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> City</label>
			<div class="division"><?php echo $this->form->city_3; ?></div>
			</div>			
			<div class="new-form-ui">
			  <label> Contact type </label>
			<div class="division"><?php echo $this->form->contact_type_3; ?></div>
			</div>
		</div>
     </div>  
 </div>     
		<div class="new-form-ui-submit">		
		<?php if($this->permission == 'Yes'){?>
		<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
		<?php } ?>		
		<button onclick="window.location.href='<?php echo BASE_URL; ?>agencylist';" id="Cancel" name="Cancel" type="button" >Cancel</button>
		</div>
</form>
</div>
<?php } ?>
<script type='text/javascript'>
$(document).ready(function() { 

if($("li.active").is(':first-child'))
{
	$('.right-block-data').addClass('right-over-border');
}else{
	$('.right-block-data').removeClass('right-over-border');
}
});
</script>