<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php
if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php 
}else
{

sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        
		    <div class="new-form-ui">
			  <label  class="required">Approve or Reject</label>
			<div class="division"><?php echo $this->form->managerstatus; ?></div>
			<?php if(isset($this->msgarray['managerstatus'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->managerstatus->getId(); ?>"><?php echo $this->msgarray['managerstatus'];?></span>
			<?php }?>
			</div>
			<div class="new-form-ui textareaheight">
			  <label>Comments</label>
			<div class="division"><?php echo $this->form->comments; ?></div>
			<?php if(isset($this->msgarray['comments'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->reason->getId(); ?>"><?php echo $this->msgarray['comments'];?></span>
			<?php }?>
			</div>
		     <div class="total-form-controller view-form-detail">
		    <div class="new-form-ui">
			  <label>Employee Name</label>
			<div class="division"><?php echo $this->form->employeename; ?></div>
			<?php if(isset($this->msgarray['employeename'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->employeename->getId(); ?>"><?php echo $this->msgarray['employeename'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label>Leave Type</label>
			<div class="division"><?php echo $this->form->leavetypeid; ?></div>
			<?php if(isset($this->msgarray['leavetypeid'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->leavetypeid->getId(); ?>"><?php echo $this->msgarray['leavetypeid'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label>Leave</label>
			<div class="division"><?php echo $this->form->leaveday; ?></div>
			<?php if(isset($this->msgarray['leaveday'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->leaveday->getId(); ?>"><?php echo $this->msgarray['leaveday'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui textareaheight">
			  <label>Reason</label>
			<div class="division"><?php echo $this->form->reason; ?></div>
			<?php if(isset($this->msgarray['reason'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->reason->getId(); ?>"><?php echo $this->msgarray['reason'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label>From Date</label>
			<div class="division"><?php echo $this->form->from_date; ?></div>
			<?php if(isset($this->msgarray['from_date'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->from_date->getId(); ?>"><?php echo $this->msgarray['from_date'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui" id="todate_employeeedit">
			  <label>To Date</label>
			<div class="division"><?php echo $this->form->to_date; ?></div>
			<?php if(isset($this->msgarray['to_date'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->to_date->getId(); ?>"><?php echo $this->msgarray['to_date'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label>Number of Days</label>
			<div class="division"><?php echo $this->form->appliedleavesdaycount; ?></div>
			<?php if(isset($this->msgarray['appliedleavesdaycount'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->appliedleavesdaycount->getId(); ?>"><?php echo $this->msgarray['appliedleavesdaycount'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label>Applied On</label>
			<div class="division"><?php echo $this->form->createddate; ?></div>
			<?php if(isset($this->msgarray['createddate'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->createddate->getId(); ?>"><?php echo $this->msgarray['createddate'];?></span>
			<?php }?>
			</div> 
			
		<!-- 	<div class="new-form-ui">
			  <label>Status</label>
			<div class="division"><?php //echo $this->form->leavestatus; ?></div>
			<?php //if(isset($this->msgarray['leavestatus'])){?>
			   <span class="errors" id="errors-<?php //echo $this->form->leavestatus->getId(); ?>"><?php //echo $this->msgarray['leavestatus'];?></span>
			<?php //}?>
			</div>   -->
			
			<div class="new-form-ui-submit">
			<?php echo $this->form->submit; ?>
			<button onclick="window.location.href='<?php echo BASE_URL; ?>manageremployeevacations';" type="button" id="Cancel" name="Cancel">Cancel</button>
			</div>
		
       </div>
</form>
<?php } ?>

<script type='text/javascript'>
$(document).ready(function(){
   <?php if($this->data['leaveday'] == 2){?>
           $("#todate_employeeedit").hide();
   <?php }?>
});
</script>

