<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}else{

sapp_Global::generateClientValidations($this->form);
if(!empty($this->employeedata)) 
{
		echo $this->employeedetails($this->employeedata,'mydetails',$this->id); 
 } ?>
<div class="right-block-data"> 
	<div id="error_message" style="display:none;"></div>
	
			<?php echo $this->form->id; ?>
			 <div class="total-form-controller cancel-set view-form-detail">
		 
			<div class="new-form-ui">
			  <label>Card Type </label>
			<div class="division loca_state_div"><?php echo $this->form->card_type; ?></div>
				
			</div>
			
			<div class="new-form-ui">
			  <label>Corporate Card Number</label>
			<div class="division"><?php echo $this->form->card_number; ?></div>
			
			</div>
			
			<div class="new-form-ui">
			  <label>Name on Card </label>
			<div class="division"><?php echo $this->form->nameoncard; ?></div>
			
			</div>
			
			<div class="new-form-ui">
			  <label>Expiry Date </label>
			<div class="division"><?php echo $this->form->card_expiration; ?></div>
			
			</div>
			
			<div class="new-form-ui">
			  <label>Card Issued By</label>
			<div class="division"><?php echo $this->form->card_issuedby; ?></div>
			
			</div>
			
			<div class="new-form-ui">
			  <label>Card Code</label>
			<div class="division"><?php echo $this->form->card_code; ?></div>
			
			</div>
			<div class="new-form-ui-submit">
			<?php	/*	If the login employee has edit privilege then show edit ...		*/
			if($this->editPrivilege == 'Yes')	{	?>
        	<input type="button" onclick="redirecttoEditscreen('<?php echo $this->controllername;?>','<?php echo $this->actionname;?>');" value="Edit" />    
		<?php	}	?>
			
			 </div>
			
        </div>
			 

</div>	
</div>


<script type="text/javascript" language="javascript">
$(document).ready(function() {
  
    $("#creditcarddetails").addClass('active');
	$("#creditcarddetails").removeAttr("onclick");

});//end of ready function

</script>

<?php }?>
