<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
					<!--No record exists-->
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}	else	{
 $baseUrl = $this->serverUrl().$this->baseUrl();
 sapp_Global::generateClientValidations($this->form);
 if($this->emptyFlag != 0)
	{
?>	 <div class="ml-alert-1-info m1-info-set">
		<div class="style-1-icon info"></div>
			The employee configurations are not yet set.Please configure them to add employee personal details.
	</div>
<?php	}	?>
<?php if (count($this->messages)) {?>
	<div id="dispemppersonal" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>
	
<?php } ?>
<?php if(!empty($this->empdata))
 {
       	echo $this->employeedetails($this->empdata[0],'mydetails',$this->id); 
 } 
?>
<div class="right-block-data">
	<div id="error_message" style="display:none;"></div>
	<?php //if(empty($this->data))	{	?>
			<!--<div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>No record exists with this id.
			</div>-->
	<?php //}else{	?>
	<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id;
          echo $this->form->user_id; 
		?>
			<div class="total-form-controller">
				<div class="new-form-ui">
				  <label class="required">Gender</label>
				<div class="division"><?php echo $this->form->genderid; ?></div>
				<?php if(isset($this->msgarray['genderid'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->genderid->getId(); ?>"><?php echo $this->msgarray['genderid'];?></span>
				<?php }?>
				</div>
				
				<div class="new-form-ui">
				  <label class="required">Marital Status</label>
				<div class="division"><?php echo $this->form->maritalstatusid; ?></div>
				<?php if(isset($this->msgarray['maritalstatusid'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->maritalstatusid->getId(); ?>"><?php echo $this->msgarray['maritalstatusid'];?></span>
				<?php }?>
				</div>
		
				<div class="new-form-ui">
			   <label class="required">Nationality</label>
				<div class="division"><?php echo $this->form->nationalityid; ?></div>
				<?php if(isset($this->msgarray['nationalityid'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->nationalityid->getId(); ?>"><?php echo $this->msgarray['nationalityid'];?></span>
				<?php }?>
				</div>
				
				<div class="new-form-ui">
			   <label ><?php echo $this->form->ethniccodeid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->ethniccodeid; ?></div>
				<?php if(isset($this->msgarray['ethniccodeid'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->ethniccodeid->getId(); ?>"><?php echo $this->msgarray['ethniccodeid'];?></span>
				<?php }?>
				</div>
				
				<div class="new-form-ui">
			   <label ><?php echo $this->form->racecodeid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->racecodeid; ?></div>
				<?php if(isset($this->msgarray['racecodeid'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->racecodeid->getId(); ?>"><?php echo $this->msgarray['racecodeid'];?></span>
				<?php }?>
				</div>
				
				<div class="new-form-ui">
			   <label ><?php echo $this->form->languageid->getLabel(); ?></label>
				<div class="division"><?php echo $this->form->languageid; ?></div>
				<?php if(isset($this->msgarray['languageid'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->languageid->getId(); ?>"><?php echo $this->msgarray['languageid'];?></span>
				<?php }?>
				</div>
				
				<div class="new-form-ui">
				  <label class="required">Date of Birth <img class="tooltip" title="<?php echo DATE_DESCRIPTION;?>" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"></label>
				<div class="division"><?php echo $this->form->dob; ?></div>
				<?php if(isset($this->msgarray['dob'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->dob->getId(); ?>"><?php echo $this->msgarray['dob'];?></span>
				<?php }?>
				</div>
												
				<div class="new-form-ui">
				  <label >Celebrated Date of Birth <img class="tooltip" title="<?php echo DATE_DESCRIPTION;?>" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"></label>
				<div class="division"><?php echo $this->form->celebrated_dob; ?></div>
				<?php if(isset($this->msgarray['celebrated_dob'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->celebrated_dob->getId(); ?>"><?php echo $this->msgarray['celebrated_dob'];?></span>
				<?php }?>
				</div>	
				
				<div class="new-form-ui">
				  <label >Blood Group</label>
				<div class="division"><?php echo $this->form->bloodgroup; ?></div>
				<?php if(isset($this->msgarray['bloodgroup'])){?>
				   <span class="errors" id="errors-<?php echo $this->form->bloodgroup->getId(); ?>"><?php echo $this->msgarray['bloodgroup'];?></span>
				<?php }?>
				</div>
				
				<?php if(!empty($this->identitydocument)) {?>
				
				        <div class="separetor-heading">Identity Documents</div>
						
						<?php if($this->identitydocument[0]['passport'] == 1){?>
						<div class="new-form-ui">
						  <label class="required">Passport Number</label>
						<div class="division"><?php echo $this->form->passport; ?></div>
						<?php if(isset($this->msgarray['passport'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->passport->getId(); ?>"><?php echo $this->msgarray['passport'];?></span>
						<?php }?>
						</div>
						<?php } ?>
						
						<?php if($this->identitydocument[0]['pancard'] == 1){?>
						<div class="new-form-ui">
						  <label class="required">Pancard Number</label>
						<div class="division"><?php echo $this->form->pancard_number; ?></div>
						<?php if(isset($this->msgarray['pancard_number'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->pancard_number->getId(); ?>"><?php echo $this->msgarray['pancard_number'];?></span>
						<?php }?>
						</div>
						<?php } ?>
						
						<?php if($this->identitydocument[0]['aadhaar'] == 1){?>				
						<div class="new-form-ui">
						  <label class="required">Aadhar Number</label>
						<div class="division"><?php echo $this->form->adhar_number; ?></div>
						<?php if(isset($this->msgarray['adhar_number'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->adhar_number->getId(); ?>"><?php echo $this->msgarray['adhar_number'];?></span>
						<?php }?>
						</div>
						<?php }?>
						
						<?php if($this->identitydocument[0]['drivinglicense'] == 1){?>  				
						<div class="new-form-ui">
						  <label class="required">Driver's License Number</label>
						<div class="division"><?php echo $this->form->drivinglicence_number; ?></div>
						<?php if(isset($this->msgarray['drivinglicence_number'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->drivinglicence_number->getId(); ?>"><?php echo $this->msgarray['drivinglicence_number'];?></span>
						<?php }?>
						</div>
						<?php }?>
						
						<?php	if($this->identitydocument[0]['ssn'] == 1){?>
						<div class="new-form-ui">
						<!--  <label class="required">SSN</label>-->
						<label class="required">Social Security Number</label>
						<div class="division"><?php echo $this->form->SSN_number; ?></div>
						<?php if(isset($this->msgarray['SSN_number'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->SSN_number->getId(); ?>"><?php echo $this->msgarray['SSN_number'];?></span>
						<?php }?>
						</div>
						<?php }?>
						
						<?php if($this->identitydocument[0]['others'] != ''){?>
						<div class="new-form-ui">
						  <label class="required"><?php echo $this->identitydocument[0]['others'];?></label>
						<div class="division"><?php echo $this->form->otheridentity; ?></div>
						<?php if(isset($this->msgarray['otheridentity'])){?>
						   <span class="errors" id="errors-<?php echo $this->form->otheridentity->getId(); ?>"><?php echo $this->msgarray['otheridentity'];?></span>
						<?php }?>
						</div>
						<?php } ?>
				
				<?php }?>
				
			</div>
						
			<div class="new-form-ui-submit">
					<?php echo $this->form->submit; ?>
					<!--<button onclick="window.location.href='/hrms/mydetails/edit';" type="button" id="Cancel" name="Cancel">Cancel</button>-->
			</div>  
  
</form>
	<?php	//}	?>
</div>	
</div>
<?php	}	?>
<script>
$(document).ready(function(){

 /* Making window responsive*/
 	var complete_empwidth = $('.emp-screen-view').width();
	$('#displayimg').css("width", "150");
	$('#personalDetailsDiv').css("width", (complete_empwidth-(152)));	
		
	 function checkempWidth() {
        var complete_empwidth = $('.emp-screen-view').width();		
		$('#displayimg').css("width", "150");
		$('#personalDetailsDiv').css("width", (complete_empwidth-(152)));		
    }
	
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispemppersonal').fadeOut('slow');
		},3000);

<?php } ?>

var yearrange = <?php echo "'".date("Y", strtotime("-30 years")).':'.date('Y')."'"; ?>;
$('#dob,#celebrated_dob').datepicker({
				showOn:'both',
				maxDate: new Date, 
				yearRange: yearrange,
				dateFormat: '<?php echo DATEFORMAT_JS;?>',
				buttonImage: "<?php echo $this->baseUrl("public/media/images/cal.jpg");?>",
				buttonImageOnly: true,
				buttonText: "",
				changeMonth: true,
				changeYear: true,
                                showButtonPanel: true ,
				onClose:function()
				{
					$(this).trigger('blur');
				}   
		});

var complete_width = $('.poc-ui-data-control').width();
	$('.left-block-ui-data').css("width", "230");
	$('.right-block-data').css("width", (complete_width-(253)));	
		
	 function checkWidth() {
        var complete_width = $('.poc-ui-data-control').width();		
		$('.left-block-ui-data').css("width", "230");
		$('.right-block-data').css("width", (complete_width-(253)));		
    }
	$(window).resize(function() {
		checkWidth();
		checkempWidth();
	});
	$("#emppersonaldetails").addClass('active');
	$("#emppersonaldetails").removeAttr("onclick");
})

</script>
