<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
					<!--No record exists-->
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}else{
	$baseUrl = $this->serverUrl().$this->baseUrl();
sapp_Global::generateClientValidations($this->form);
if($this->form->emptyFlag->getValue() != 0)
	{
?>	 <div class="ml-alert-1-info m1-info-set">
		<div class="style-1-icon info"></div>
			The employee configurations are not yet set.Please configure them to add employee work eligibility details.
	</div>
<?php	}	?>
<div id="error_message" style="display:none;"></div>
<?php if (count($this->messages)) {?>
	<div id="dispempwork" class="settingssuccess">
		<?php 
			foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			} 
		?>
	</div>
	
<?php } ?>
<?php if(!empty($this->empdata))
 {
       	echo $this->employeedetails($this->empdata[0],'mydetails',$this->id); 
 } 
?>
<div class="right-block-data"> 

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; 
		      echo $this->form->issuingauthflag;
		?>
        <div class="total-form-controller">
		 
			<div class="new-form-ui">
			  <label>Document Type </label>
			<div class="division loca_state_div"><?php echo $this->form->documenttype_id; ?></div>
			<?php if($this->form->emptyFlag->getValue() != 0)	{	?>
				<span class="errors" id="err_<?php echo $this->form->documenttype_id->getId(); ?>">Work eligibility document types are not configured yet.</span>
			<?php	}	?>
			<?php if(isset($this->msgarray['documenttype_id'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->documenttype_id->getId(); ?>"><?php echo $this->msgarray['documenttype_id'];?></span>
			<?php }?>
			</div>
			
			<div class="new-form-ui">
			  <label>Document Issue Date </label>
			<div class="division"><?php echo $this->form->doc_issue_date; ?></div>
			<?php if(isset($this->msgarray['doc_issue_date'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->doc_issue_date->getId(); ?>"><?php echo $this->msgarray['doc_issue_date'];?></span>
			<?php }?>
			
			</div>
			
			
			<div class="new-form-ui">
			  <label>Document Expiry Date </label>
			<div class="division"><?php echo $this->form->doc_expiry_date; ?></div>
			 <?php if(isset($this->msgarray['doc_expiry_date'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->doc_expiry_date->getId(); ?>"><?php echo $this->msgarray['doc_expiry_date'];?></span>
			<?php }?>
			</div>
			<div class="new-form-ui">
			  <label>Issuing Authority Name </label>
				<div class="division"><?php echo $this->form->issuingauth_name; ?></div>
			</div>
			
			<div class="new-form-ui">
				<label>Issuing Authority Country</label>
				<div class="division"><?php echo $this->form->issuingauth_country; ?></div>
			</div>
			
					
			<div class="new-form-ui" id="issuingauth_statediv">
			  <label>Issuing Authority State</label>
				<div class="division"><?php echo $this->form->issuingauth_state; ?></div>
			</div>
			
			
			<div class="new-form-ui" id="issuingauth_citydiv">
			  <label>Issuing Authority City</label>
			<div class="division"><?php echo $this->form->issuingauth_city; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Issuing Authority Postal Code</label>
			<div class="division"><?php echo $this->form->issuingauth_postalcode; ?></div>
			</div>
			
		     <div class="new-form-ui-submit">
		<?php	/*	If the login employee has edit privilege then show edit ...		*/
			if($this->editPrivilege == 'Yes')	{	?>
        	<input type="button" onclick="redirecttoEditscreen('<?php echo $this->controllername;?>','<?php echo $this->actionname;?>');" value="Edit" />    
		<?php	}	?>   
			</div>
     </div>
</form>

</div>
</div>


<script>
$(document).ready(function(){
		<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispempwork').fadeOut('slow');
		},3000);

<?php } ?>
		
	$("#workeligibilitydetails").addClass('active');
	$("#workeligibilitydetails").removeAttr("onclick");
	
	<?php if ($this->issuingauthority !='') {
	      if ($this->issuingauthority == 1){
    ?>		  
			$("#issuingauth_statediv").hide();
			$("#issuingauth_citydiv").hide();

    <?php }else if ($this->issuingauthority == 2){
    ?>
		  $("#issuingauth_statediv").show();
		  $("#issuingauth_citydiv").hide();
		  
    <?php } else if ($this->issuingauthority == 3) {?>
	      $("#issuingauth_statediv").show();
		  $("#issuingauth_citydiv").show();
	<?php }?>
        
    <?php }?>
	
	
	});
</script>
<?php }?>