<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if(!empty($this->statesmodeldata))
{
	if($this->con == 'state')
	{
		foreach ($this->statesmodeldata as $state) {
			$this->statesform->state->addMultiOption($state['state_id_org'].'!@#'.$state['state'],utf8_encode($state['state']));
		}
		echo $this->statesform->state;
	}
	else
	{
		foreach ($this->statesmodeldata as $state) {
			$this->statesform->state->addMultiOption($state['id'].'!@#'.$state['state_name'],utf8_encode($state['state_name']));
		}
		if($this->con != 'nootheroption')
		 $this->statesform->state->addMultiOption('other','Other');
		echo $this->statesform->state;
	}
}else
{
 echo "nostates";
}	
?> 
 