<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
					<!--No record exists-->
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}	else	{
 $baseUrl = $this->serverUrl().$this->baseUrl();
sapp_Global::generateClientValidations($this->form);
?>
<div id="error_message" style="display:none;"></div>

<?php if(!empty($this->employeedata)) 
{
	echo $this->employeedetails($this->employeedata,'view',$this->id); 
}
 ?>

<div class="right-block-data"> 
	<?php	if(empty($this->data))
	{?><div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>Visa and Immigration details are not configured yet.
			</div>
	<?php	}	else	{	?>
		<?php echo $this->form->id; ?>
        <div class="total-form-controller cancel-set view-form-detail">
		 
			<div class="new-form-ui">
			  <label>Passport Number </label>
			<div class="division loca_state_div"><?php echo $this->form->passport_number; ?></div>
			
			</div>
			
			<div class="new-form-ui ">
			  <label>Passport Issued Date<!-- <img class="tooltip" title=" mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> --></label>
			<div class="division"><?php echo $this->form->passport_issue_date; ?></div>
			</div>
			
			
			<div class="new-form-ui ">
			  <label>Passport Expiry Date<!-- <img class="tooltip" title=" mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> --></label>
			<div class="division"><?php echo $this->form->passport_expiry_date; ?></div>
			
			</div>
			<div class="new-form-ui ">
			  <label>Visa Type Code</label>
			<div class="division"><?php echo $this->form->visa_type; ?></div>
			
			</div>
			
			<div class="new-form-ui ">
			  <label>Visa Number </label>
			<div class="division"><?php echo $this->form->visa_number; ?></div>
			
			</div>
			
					
			<div class="new-form-ui ">
			  <label>Visa Issued Date<!-- <img class="tooltip" title=" mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> --></label>
			<div class="division"><?php echo $this->form->visa_issue_date; ?></div>
			 
			</div>
			
			
			<div class="new-form-ui ">
			  <label>Visa Expiry Date<!-- <img class="tooltip" title=" mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> --></label>
			<div class="division"><?php echo $this->form->visa_expiry_date; ?></div>
			
			</div>
			
			<div class="new-form-ui ">
			  <label>I-9 Status </label>
			<div class="division"><?php echo $this->form->inine_status; ?></div>
			
			</div>
			
			<div class="new-form-ui ">
			  <label>I-9 Review Date<!-- <img class="tooltip" title=" mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> --></label>
			<div class="division"><?php echo $this->form->inine_review_date; ?></div>
			
			</div>
			<div class="new-form-ui ">
			  <label>Issuing Authority</label>
			<div class="division"><?php echo $this->form->issuing_authority; ?></div>
			
			</div>
			
			<div class="new-form-ui ">
			  <label>I-94 Status </label>
			<div class="division"><?php echo $this->form->ininetyfour_status; ?></div>
			
			</div>
			
			<div class="new-form-ui ">
			  <label>I-94 Expiry Date<!-- <img class="tooltip" title=" mm-dd-yyyy" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"> --></label>
			<div class="division"><?php echo $this->form->ininetyfour_expiry_date; ?></div>
			
			</div>	
			 <div class="new-form-ui-submit">
			<!--<input onclick="window.location.href='/hrms/employee';" type="button" id="Cancel" name="Cancel" value = "Back"/>-->
			</div>
			
        </div>
        
<?php	}	?>
</div>
</div>

<script>
$(document).ready(function(){
		
	/* Making window responsive
 	var complete_width = $('.poc-ui-data-control').width();
	$('.left-block-ui-data').css("width", "230");
	$('.right-block-data').css("width", (complete_width-(253)));	
		
	 function checkWidth() {
        var complete_width = $('.poc-ui-data-control').width();		
		$('.left-block-ui-data').css("width", "230");
		$('.right-block-data').css("width", (complete_width-(253)));		
    }
	$(window).resize(function() {
		checkWidth();
	}); */
	
	$("#visadetails").addClass('active');
    $("#visadetails").removeAttr("onclick"); 
	
	
	});
</script>

<?php	}	?>