<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
//echo $this->message;
?>

<div class="total-form-controller">
<div class="separetor-heading">Interview Details</div>
	<div class="new-form-ui">
            <label class="required">Requisition ID</label>
            <div class="division"><select></select></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Candidate ID</label>
            <div class="division"><select></select></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Interviewer</label>
            <div class="division"><select></select></div>
    </div>
  	<div class="new-form-ui">
            <label class="required">Interviewer Status</label>
            <div class="division"><select></select></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Location</label>
            <div class="division"><input type="text" /></div>
    </div>
       <div class="new-form-ui">
            <label class="required">Interview Type</label>
              <div class="division"><select></select></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Interview Time</label>
            <div class="division"><input type="text" /></div>
    </div>
    <div class="new-form-ui">
            <label class="required">Interview Date <img class="tooltip" title="<?php echo DATE_DESCRIPTION;?>" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
            <div class="division"><input type="text" /></div>
    </div>

<div class="separetor-heading">Round : Round 1</div>

	<div class="new-form-ui">
            <label class="required">Candidate Name</label>
            <div class="division"><span class="textarea-data-show">[cand. name]</span></div>
    </div>
    
	<div class="new-form-ui">
            <label class="required">Email Id</label>
            <div class="division"><span class="textarea-data-show">[mail]</span></div>
    </div>

	<div class="new-form-ui">
            <label class="required">Qualification</label>
            <div class="division"><span class="textarea-data-show">[qualification]</span></div>
    </div>

	<div class="new-form-ui">
            <label class="required">Work Experience</label>
            <div class="division"><span class="textarea-data-show">[work exp]</span></div>
    </div>

	<div class="new-form-ui textareaheight">
            <label class="required">Skill Set</label>
            <div class="division">
            <span class="textarea-data-show">Contrary to popular belief
            Lorem Ipsum is
            not simply random text. 
            It has roots in a piece 
            of classical Latin literature</span></div>
    </div>
	<div class="new-form-ui textareaheight">
            <label class="required">Summary</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
    </div>
	<div class="new-form-ui textareaheight">
            <label class="required">Education Summary</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature , It has roots in a piece of classical Latin literature, It has roots in a piece of classical Latin literature, It has roots in a piece of classical Latin literature</span></div>
    </div>

<div class="separetor-heading">Feedback Details</div>

  	<div class="new-form-ui">
            <label class="required">Round 1</label>
            <div class="division"><select></select></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Interviewer</label>
            <div class="division"><input type="text" /></div>
    </div>

  	<div class="new-form-ui">
            <label class="required">Interviewer Type</label>
            <div class="division"><select></select></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Location</label>
            <div class="division"><input type="text" /></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Interview Time</label>
            <div class="division"><input type="text" /></div>
    </div>

        <div class="new-form-ui">
            <label class="required">Interview Date</label>
            <div class="division"><input type="text" /></div>
    </div>

	<div class="new-form-ui textareaheight">
            <label class="required">Interviewer Feedback</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
    </div>

	<div class="new-form-ui textareaheight">
            <label class="required">Interviewer Comments</label>
            <div class="division"><span class="textarea-data-show">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature</span></div>
    </div>
  	<div class="new-form-ui">
            <label class="required">Result Status</label>
            <div class="division"><select></select></div>
    </div>
        <div class="new-form-ui">
            <label class="required">Interview Type</label>
            <div class="division"><input type="text" /></div>
    </div>

<div class="new-form-ui-submit">
		<input type="submit" value="save" />
		<button type="button" id="Cancel" name="Cancel">Cancel</button>
</div>  


</div>