<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
  	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
$data = $this->data; ?>
    <div class="total-form-controller view-form-detail">
		
		<div style="margin-left: 0px; padding-top: 0px; padding-bottom: 20px;  float: none;" class="cofig_title">Client
			<div style="margin-top: 0px; float: right; width: auto;" class="new-form-ui-submit ">
				<!--<div style="position: relative; float: right; top: 0px;" class="back-to-page">
					<input type="button" style="margin-right: 0px;" value="Back" name="Back" onclick="window.location.href='<?php// echo BASE_URL; ?>default/clients';">
				</div>-->
				
				<!--<input type="button"  class="fltright" onclick="changeeditscreen('<?php// echo $this->controllername;?>',<?php //echo $this->id;?>);" value="Edit" />-->
				<?php if(Zend_Registry::get( 'tm_role' ) != 'Employee')
				{?>
			
				<!--<input type="button"  class="fltright" onclick="window.location.href='<?php //echo BASE_URL; ?>clients/edit/id/<?php //echo $this->id;?>';" value="Edit" />-->
				<?php $msgtitle = $this->controllername.'_delete';
				sapp_Helper::editdeleteForView("",$this->controllername,$this->id,$msgtitle,$isfromTM=1);?>
				<?php } ?>
				
			</div>
		 </div>
		 <?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Client ',(!empty($this->data[0]['client_name']))?$this->data[0]['client_name']:"...",'Address',(!empty($this->data[0]['address']))?$this->data[0]['address']:"...");
sapp_Helper::viewBody('nor','Country',(!empty($this->data[0]['country_name']))?$this->data[0]['country_name']:"...",'State',(!empty($this->data[0]['state_name']))?$this->data[0]['state_name']:"...");
sapp_Helper::viewBody('alt','Email',(!empty($this->data[0]['email']))?$this->data[0]['email']:"...",'Phone Number',(!empty($this->data[0]['phone_no']))?$this->data[0]['phone_no']:"...");
sapp_Helper::viewBody('nor','Fax',(!empty($this->data[0]['fax']))?$this->data[0]['fax']:"...",'Point of Contact',(!empty($this->data[0]['poc']))?$this->data[0]['poc']:"..."); 
sapp_Helper::viewFooter();
?>

	</div>       
<?php	}	?> 

<?php 
		if($this->projectData>0) { 
 
	if($this->call == 'ajaxcall'){
		$div = ''; $endDiv = ''; 
	} else { 
		$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
	}
		echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
	}  
		?>

		<div id="departmentsContainer"  style="display: none; overflow: auto;">
			<div class="heading">
				<a href="javascript:void(0)">
				<img src="<?php echo MEDIA_PATH; ?>images/close.png" name="" align="right"
					border="0" hspace="3" vspace="5" class="closeAttachPopup"
					style="margin: -24px 8px 0 0;"> </a>
			</div>
				<iframe id="departmentsCont" class="business_units_iframe" frameborder="0"></iframe>
		</div>






<script type="text/javascript" language="javascript">
$(document).ready(function(){
	$('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>default/clients'></a>");
});
</script>  
 
 