<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{

if($this->emailContactsData == '' || empty($this->emailContactsData)) { ?>
			No Data Found
<?php }else { ?>
 <div class="total-form-controller">
		 
			<div class="new-form-ui clearb">
			  <label>Business Unit</label>
			<div class="division loca_state_div"><?php echo $this->form->business_unit_id; ?></div>
			<span class="errors" id="errors-business_unit_id"></span>
			</div>		
            <div class="new-form-ui clearb">
			  <label class="required">Group</label>
			<div class="division loca_state_div"><?php echo $this->form->group_id; ?></div>
			<div class="errors" id="errors-group_id"></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label class="required">Group Email </label>
			<div class="division"><?php echo $this->form->groupEmail; ?></div>
			 <div class="errors" id="error_groupEmail" ></div>
			</div>
			
        </div>
	
		<div class="new-form-ui-submit">
        <input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
        
        <button onclick="window.location.href='<?php echo BASE_URL; ?><?php echo $this->controllername;?>';" type="button" id="Cancel" name="Cancel">Cancel</button>
        </div>
</form>
</div>
<?php }} ?>
