<?php
/*********************************************************************************
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php
}
else
{	sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller">
		    <div class="new-form-ui">
			  <label class="required">Oncall Type <img class="tooltip" title="Ex: Sick Oncall, Pregnancy-Disability and Child Care Oncall" src="<?php echo MEDIA_PATH;?>images/help.png"></label>
			<div class="division"><?php echo $this->form->oncalltype; ?></div>
			<?php if(isset($this->msgarray['oncalltype'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->oncalltype->getId(); ?>"><?php echo $this->msgarray['oncalltype'];?></span>
			<?php }?>
			</div>

			<div class="new-form-ui">
			  <label class="required">Number of Days</label>
			<div class="division"><?php echo $this->form->numberofdays; ?></div>
			<?php if(isset($this->msgarray['numberofdays'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->numberofdays->getId(); ?>"><?php echo $this->msgarray['numberofdays'];?></span>
			<?php }?>
			</div>

			<div class="new-form-ui">
			  <label >Oncall Short Code</label>
			<div class="division"><?php echo $this->form->oncallcode; ?></div>
			<?php if(isset($this->msgarray['oncallcode'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->oncallcode->getId(); ?>"><?php echo $this->msgarray['oncallcode'];?></span>
			<?php }?>
			</div>
			<div class="new-form-ui">
			  <label >Is Pre Allocated</label>
			<div class="division"><?php echo $this->form->oncallpreallocated; ?></div>
			</div>
			<div class="new-form-ui">
			  <label >Is Deductible</label>
			<div class="division"><?php echo $this->form->oncallpredeductable; ?></div>
			</div>

			<div class="new-form-ui textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>employeeoncalltypes';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
</div>
</form>
<?php	}	?>
