<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php // Start :Condition to check whether organisation is created or not
    if($this->orgdata !='' && $this->orgdata == 'noorgdata'){?>
    <div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>	
	Organization information is not added yet.
			
</div>
<?php
}else
{
		 if($this->ermsg == 'nodata') { ?>
		<div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
		<?php } else { 
		$baseUrl = $this->serverUrl().$this->baseUrl();
		echo $this->form->id; ?>
		<span id="error_message"></span>
				<div class="total-form-controller view-form-detail cancel-set">
					<div class="new-form-ui">					 
					  <label>Name</label>
					<div class="division"><?php echo $this->form->unitname; ?></div>
					</div>
					
					<div class="new-form-ui">					  
					  <label>Code</label>
					<div class="division"><?php echo $this->form->unitcode; ?></div>
					</div>
					
					<div class="new-form-ui textareaheight">
					  <label>Description</label>
					<div class="division"><?php echo $this->form->description; ?></div>
					</div>
					<div class="new-form-ui">
					  <label>Started On </label>
					<div class="division"><?php echo $this->form->start_date;?></div>
					</div>
					
					<div class="new-form-ui">
					  <label>Time Zone</label>
					<div class="division"><?php echo $this->form->timezone; ?></div>
					</div>	
					
					<div class="new-form-ui">
					  <label>Country</label>
					<div class="division"><?php echo $this->form->country;?></div>
					</div>
					
					<div class="new-form-ui">
					  <label>State</label>
					<div class="division"><?php echo $this->form->state;?></div>
					</div>
					
					<div class="new-form-ui">
					  <label>City</label>
					<div class="division"><?php echo $this->form->city;?></div>
					</div>
					
					<div class="new-form-ui textareaheight">
					  <label>Street Address 1</label>
					<div class="division"><?php echo $this->form->address1; ?></div>
					</div>
					
					<div class="new-form-ui textareaheight">
					  <label>Street Address 2</label>
					<div class="division"><?php echo $this->form->address2; ?></div>
					</div>
					
					<div class="new-form-ui textareaheight">
					  <label>Street Address 3</label>
					<div class="division"><?php echo $this->form->address3; ?></div>
					</div>
					
					<div class="new-form-ui-submit">
						<?php if(($this->editpermission == 'Yes')) { ?>
							 <input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
							<button onclick="window.location.href='<?php echo $this->baseUrl();?>/businessunits';" type="button" >Cancel</button>
						   <?php }
						   else{
							?>
							<input type="button" onclick="window.location.href='<?php echo $this->baseUrl();?>/businessunits';" type="button"  value="Back"  />
						   <?php } ?>
						
					</div>
				</div>
		
		<?php 
		if($this->deptData>0) { 
		if($this->call == 'ajaxcall'){
			$div = ''; $endDiv = ''; 
		} else { 
			$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
		}
			echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
		}
		?>

		<div id="departmentsContainer"  style="display: none; overflow: auto;">
			<div class="heading">
				<a href="javascript:void(0)">
				<img src="<?php echo MEDIA_PATH; ?>images/close.png" name="" align="right"
					border="0" hspace="3" vspace="5" class="closeAttachPopup"
					style="margin: -24px 8px 0 0;"> </a>
			</div>
				<iframe id="departmentsCont" class="business_units_iframe" frameborder="0"></iframe>
		</div>
		<script type='text/javascript'>
		$(document).ready(function(){
				<?php 
					for($i=1;$i<=3;$i++)
					{	
						if (!empty($this->msgarray)) 
						{?>
							$('#country').val('');
							$('#state').val('');
							$('#s2id_state .select2-choice span').html('Select state');
							$('#s2id_country .select2-choice span').html('Select country');										   
				<?php 	
						} 
					}	?>
			});
		</script>
<?php } 
}// End :Condition to check whether organisation is created or not
?>