<?php
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2015 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/ 
 
	
	$storage = new Zend_Auth_Storage_Session();
	$data = $storage->read();
	$request = Zend_Controller_Front::getInstance();
	$controllerName = $request->getRequest()->getControllerName();
        
        
        
	if($data != "") {
		if($controllerName == 'wizard')
			include "wizardheader.phtml";
		else
			include "analyticsheader.phtml";
	} 
	else {       
		include "defaultheader.phtml";
	}
?>

<?php echo $this->layout()->content; ?>
<?php 
if($data != "") {
	if($controllerName == 'wizard')
		include "wizardfooter.phtml";
	else		
		include "hrmsfooter.phtml";
}
else
{
	include "defaultfooter.phtml";
}
?>