<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<?php
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/ 
?>

<?php

$status =  sapp_Global::_checkstatus();
if($status == 'false')
{
    sapp_Global::_logout();
}
$request = Zend_Controller_Front::getInstance();
$controllerName = $request->getRequest()->getControllerName();
$actionName = $request->getRequest()->getActionName();
$baseUrl = rtrim(BASE_URL, '/');
$auth = Zend_Auth::getInstance();

$loginUserName = ""; 
$loginUserId = '';
$tourflag = 0;
$loginProfileImgSrc = MEDIA_PATH.'images/default-profile-pic.jpg';
$loginuserRole = '';
$userfullname = '';
$loginuserGroup = '';

if($auth->hasIdentity())
{	
    $loginUserId = $auth->getStorage()->read()->id;

   	/**
   	 * Handle error event on loading 'Profile image'.
   	 * file_exists() was used to avoid Network error in browser console
   	 */
	 $userProfileImage = $auth->getStorage()->read()->profileimg;
    if (!empty($userProfileImage) && file_exists("public/uploads/profile/".$userProfileImage)) {
    	$loginProfileImgSrc = DOMAIN."public/uploads/profile/".$userProfileImage;
    }
    $loginUserName =$auth->getStorage()->read()->employeeId;	    
    $loginuserRole = $auth->getStorage()->read()->emprole;
    $loginuserGroup = $auth->getStorage()->read()->group_id;
    $tourflag = $auth->getStorage()->read()->tourflag;
    $userfullname = $auth->getStorage()->read()->userfullname;
	
	
	

}
 
$storage = new Zend_Auth_Storage_Session();
$data = $storage->read();



?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="expires" content="0">
<meta name="msapplication-tap-highlight" content="no" /> 
<title><?php echo APPLICATION_NAME; ?> - Open Source HRMS</title>
<meta http-equiv="Content-type" content="text/html; charset=UTF-8 " />
<meta http-equiv="Content-Language" content="en-us" />
<link rel="shortcut icon" href="<?php echo MEDIA_PATH;?>images/favicon.ico?v=2" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/fonts.css" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/style.css" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/jquery.simplyscroll.css" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/jquerytour.css" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/jquery.jqplot.min.css" />
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/jquery.maxlength.css" />
<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css"	href="<?php echo MEDIA_PATH; ?>css/select2.css"/>
<link href="<?php echo MEDIA_PATH; ?>jquery/css/cupertino/jquery-ui-1.8.16.custom.css" media="screen" rel="stylesheet" type="text/css" >
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/tablecss.css" />
<link href="<?php echo MEDIA_PATH; ?>css/jquery.alert.css"	rel="stylesheet" type="text/css" />

<link href="<?php echo MEDIA_PATH; ?>css/responsive-calendar.css"	rel="stylesheet" type="text/css" />

<style type='text/css'>
/* To hide search bar by default */
.ui-search-toolbar { display: none; }

/* Slim scroll bar */
.slimScrollDiv { border: 0; /* margin:10px; */ }
#content_scroll { padding-bottom : 10px !important;}

/* leaf element arrow*/
.childelement {	background : none !important;}
.dragableBox li a{cursor:move !important;}

.no_selection {
    -webkit-user-select: none; /* webkit (safari, chrome) browsers */
    -moz-user-select: none; /* mozilla browsers */
    -khtml-user-select: none; /* webkit (konqueror) browsers */
    -ms-user-select: none; /* IE10+ */
}
</style>


<script type="text/javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery-ui-1.10.3.custom.js"></script> 
<script type="text/javascript" src="<?php echo MEDIA_PATH;?>js/jquery.simplyscroll.js"></script> 
<script type="text/javascript" src="<?php echo MEDIA_PATH;?>js/excanvas.js"></script>
<script type="text/javascript" language="javascript" src="<?php  echo MEDIA_PATH; ?>js/ajaxupload.3.5.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/jquery.alert.js"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/slimScrollHorizontal.js"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/jquery.slimscroll.min.js"></script>
<!-- start of time picker -->
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery.ui.timepicker.js?v=0.3.2"></script>
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery.plugin.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery.maxlength.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH;?>js/facescroll.js"></script>
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH;?>js/jquery.ui.touch-punch.min.js"></script>


    <link rel="stylesheet" href="<?php echo MEDIA_PATH?>css/screen.css">
    <link rel="stylesheet" href="<?php echo MEDIA_PATH?>css/grid.css">
    <link rel="stylesheet" href="<?php echo MEDIA_PATH?>css/fonts.css">
    <link rel="stylesheet" href="<?php echo MEDIA_PATH?>css/font-awesome.css">
    <link rel="stylesheet" href="<?php echo MEDIA_PATH?>css/glyphicon.css">
	

	
	<script type="text/javascript" language="javascript" src="<?php echo ASSETS_MEDIA_PATH?>js/assets.js"></script>


<link href="<?php echo MEDIA_PATH;?>css/jquery.ui.timepicker.css?v=0.3.2" rel="stylesheet" type="text/css" />
<!-- end of time picker -->
<script  language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH;?>jquery/js/select2.js" ></script>
<script type="text/javascript" src="<?php echo SCRIPTS_PATH;?>jquery.fileDownload-master/src/Scripts/jquery.fileDownload.js"></script>

<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/custom.css" />
<link rel="stylesheet" href="<?php echo MEDIA_PATH; ?>uniform/uniform.css" type="text/css" media="screen" />

<!-- start of jq pagination -->
<script type="text/javascript" language="javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery.jqpagination.js"></script>
<link href="<?php echo MEDIA_PATH;?>css/jqpagination.css" rel="stylesheet" type="text/css" />
<!-- end of jq pagination -->

<script type="text/javascript" src="<?php echo MEDIA_PATH;?>jquery/js/jquery.powertip.js"></script>
<link href="<?php echo MEDIA_PATH;?>css/jquery.powertip.css" rel="stylesheet" type="text/css" />


<link rel="stylesheet" type="text/css" href="<?php echo TM_MEDIA_PATH?>css/style.css" />



     <script src="<?php echo ASSETS_MEDIA_PATH;?>js/materialize.js"></script>
    <script src="<?php echo ASSETS_MEDIA_PATH;?>js/scripts.js"></script>
	
<script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/slimScrollHorizontal.js"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/jquery.slimscroll.min.js"></script>

<script type="text/javascript" language="javascript" src="<?php echo ASSETS_MEDIA_PATH?>js/assets.js"></script>

<script type="text/javascript" charset="utf-8">
$(function() {
	setTimeout('hideMessg()',3000);
});
function hideMessg() {
    if($("#messageData").is(":visible"))
	  $('#messageData').fadeOut('slow','swing');
}
// defining the project name for using in js files
var projectPath =  '/<?php echo APPLICATION_NAME; ?>/';
var application_name = '<?php echo APPLICATION_NAME; ?>';
var module_name = '/<?php echo $module; ?>';
//console.log(module_name);
<?php 
 	$controllerLi = $controllerName;?>
$(document).ready(function(){
	/* menu highlight*/
	var controllerName = '<?php echo $controllerLi;?>';
	
	   $('.reports-div').removeClass('active');
	   $('#'+controllerName+'li').addClass('active');
	/*end menu highlight*/
	
	var tmPageUrl = window.location.href;
	var controllerArray  = ["clients", "configuration", "BMW"];
	$('.logoutdiv').hide(); 			
	/* Added By sapplica, for logout dropdown */
	$(document).click(function(e)  {
		if(e.target.id == "logoutbutton" || e.target.id == "profile_img" || e.target.id == "prof_name" || e.target.id == 'b_id')
		{
		  if($("#logoutid").is(":visible"))
			$("#logoutid").hide();
		  else $("#logoutid").show();
		}
		else if(e.target.id !== "logoutid"  && e.target.id !== "profile_img" && e.target.id !== "prof_name" && e.target.id !== 'b_id')
		{
		  $("#logoutid").hide();
		}
	});
  /* End of logout dropdown */
  
  /* Making window responsive*/
  
  	var window_width = $(window).width();
	
	var content_inners_width = window_width*(99/100);
	$('.content_inners').css("width", content_inners_width);
	// For reports setting the width
	$('.wrapperdivright').css("width",'100%');
	var total_width = $('.reports-grid-ctrl').width();				
	$('.left-config-ctrl').css("width", "202");
	$('.right-config-ctrl').css("width", (total_width-250));
		
    function checkmainWidthReport() 
    {
       var window_width = $(window).width();
       var content_inners_width = window_width*(99/100);
       $('.content_inners').css("width", content_inners_width);		
       $('.wrapperdivright').css("width",'100%');			
       var total_width = $('.reports-grid-ctrl').width();					
       $('.left-config-ctrl').css("width", "202");
       $('.right-config-ctrl').css("width", (total_width-250));	

    }
	 $(window).resize(function() 
    {		
       checkmainWidthReport();		
       $("#scroller").simplyScroll({
                auto: false,
                speed: 10
       });
    });
	    
  /* End of Making window responsive */      	
	// Making forms containing tabs - responsive
	
    $('#tabContainer > ul').attr('id','tabContainerDiv');
	
    var maincontentdiv_width = $('#maincontentdiv').width();
    $('#tabContainer').css("width", maincontentdiv_width);
    $('#tabContainer > ul').css("width", "201");
    $('div[id^="tabContainer-frag-"]').css("width", (maincontentdiv_width-244));
	
    $(window).resize(function() {
        var maincontentdiv_width = $('#maincontentdiv').width();
        $('#tabContainer').css("width", maincontentdiv_width);
        $('#tabContainer > ul').css("width", "201");
        $('div[id^="tabContainer-frag-"]').css("width", (maincontentdiv_width-244));	
    });			
	
});//end of ready function

$(document).ready(function(e){
		
    $(".profile-tabs-left a").click(function(e){ 
        if(parseFloat($.trim(e.which)) != 2 && !e.ctrlKey)
        { 
            $.blockUI({ width:'50px',message: $("#spinner").html() });
        } 
        if(parseFloat($.trim(e.which)) == 2)
        {
            $.unblockUI();
        } 
    });
					 
    $(".settings").click(function(e)
    { 
        if(parseFloat($.trim(e.which)) != 2 && !e.ctrlKey)
        { 
            $.blockUI({ width:'50px',message: $("#spinner").html() });
        } 
        if(parseFloat($.trim(e.which)) == 2 || parseFloat($.trim(e.which)) == 0)
        {
            $.unblockUI();
        }
    });

    $(".configurewizard").click(function(e)
    	    { 
    	        if(parseFloat($.trim(e.which)) != 2 && !e.ctrlKey)
    	        { 
    	            $.blockUI({ width:'50px',message: $("#spinner").html() });
    	        } 
    	        if(parseFloat($.trim(e.which)) == 2 || parseFloat($.trim(e.which)) == 0)
    	        {
    	            $.unblockUI();
    	        }
    	    });
	
    $("#logoutid a").click(function(e)
    { 		    	
        if(parseFloat($.trim(e.which)) != 2 && !e.ctrlKey)
        { 
            $.blockUI({ width:'50px',message: $("#spinner").html() });
        } 
        if(parseFloat($.trim(e.which)) == 2)
        {
            $.unblockUI();
        } 					
    });	
	
    $('.logo').click(function(e) 
    { 
        if(parseFloat($.trim(e.which)) != 2 && !e.ctrlKey)
        { 
            $.blockUI({ width:'50px',message: $("#spinner").html() });
        } 
        if(parseFloat($.trim(e.which)) == 2 || parseFloat($.trim(e.which)) == 0)
        {
            $.unblockUI();
        } 					
    });
		
    $('.firstbreadcrumb').click(function() { 
        $.blockUI({ width:'50px',message: $("#spinner").html() });
    });

    $('#Save').click(function() { 
        $('.wrapperdivright').block({width:'50px',message: $("#spinner").html() }); 
    });	

    $('#Cancel').click(function() { 
        $('.wrapperdivright').block({message: $("#spinner").html() }); 
    });	
    $('#cancelwidget').click(function() { 
        $('.wrapperdivright').block({message: $("#spinner").html() }); 
    });		
		
    $('#Edit').click(function() { 
        $('.wrapperdivright').block({message: $("#spinner").html() }); 
    });	
    $("#submitbutton").click(function(){ 
        $.blockUI({ width:'50px',message: $("#spinner").html() });
    });
    $(".clssbmtbtn").not('#idbtn').click(function(){ 
        $.blockUI({ width:'50px',message: $("#spinner").html() });
    });
    $("#submit-button2,#configwizard").click(function(){ 
    	$.blockUI({ width:'50px',message: $("#spinner").html() });
    });

    $(document).ajaxStart(function(){ 		
        checkisactivestatus();
    });		
    $(document).ajaxSuccess(function(event, request, settings)
    {				
        var response = request.responseText;
        if(response == '{"login":"failed"}')
        {
            window.location.href = '<?php echo $this->serverUrl().$this->baseUrl();?>';
        }
    });	
    $(document).ajaxStop($.unblockUI); 
    $(document).ajaxError($.unblockUI);
	
		$("select:not(.not_appli)").select2({
        formatResult: format_select,            
        escapeMarkup: function(m) { return m; }
    });

    function checkisactivestatus()
    {		
        $.ajax({
            type:"post",		
            url:base_url+'/index/checkisactivestatus',
            dataType:'json',
            success: function(response)
            {
                if(response['result'] == 'false')
                {
                    window.location.href = base_url+'/index/';
                }
            }
        });
    }
    
    function format_select(selData) 
    {
	var parent_id = selData.element[0].parentElement.id;
	
        var sel_array = new Array('approver1','approver2','approver3','reporting_id','interviewer_id','reporting_manager','employee');
        if(jQuery.inArray(parent_id,sel_array) >=0)
        {
            if(parent_id == 'employee')
            {
                var title = '';
                var emp_split = selData.id.split('-');
                var textData = selData.text;

                if (selData.id == 0) return selData.text; 
                if(emp_split[0] == 'cand')
                {
                    title = 'candidate-profile_pic.jpg';					
                }
                else if(emp_split[0] == 'emp')
                {
                    title = $('#'+parent_id+' option[value="'+selData.id+'"]').attr('title');
                }
                else 
                    title = '';
                return "<img class='flag' src='<?php echo DOMAIN; ?>public/uploads/profile/"+title+"' onerror=\"this.src='<?php echo DOMAIN; ?>public/uploads/profile/profile_pic.png'\" />" + "<span>" + textData + "</span><div class='seldivimg'></div>";
            }
            else
            {
                var title = $('#'+parent_id+' option[value="'+selData.id+'"]').attr('title');
                if (!selData.id) return selData.text; 
			
                if(title == '')
                    title = "profile_pic.png";
                return "<img class='flag' src='<?php echo DOMAIN; ?>public/uploads/profile/"+title+"' onerror=\"this.src='<?php echo DOMAIN; ?>public/uploads/profile/profile_pic.png'\" />" + "<span>" + selData.text + "</span><div class='seldivimg'></div>";
            }
        }
        else 
        {
            return  "<span>" + selData.text + "</span><div class='seldivimg'></div>";
        }            
    }

// Maxlength Attributes

// Removing maxlength attributes in grids
$("table th .maxlength-feedback").remove();
	});


<?php if($actionName !='browserfailure'){?>
$(document).ready(function(){
    		
    navigator.sayswho= (function(){
        var N= navigator.appName, ua= navigator.userAgent, tem;
        var M= ua.match(/(opera|chrome|safari|firefox|msie)\/?\s*(\.?\d+(\.\d+)*)/i);
        if(M && (tem= ua.match(/version\/([\.\d]+)/i))!= null) M[2]= tem[1];
        M= M? [M[1], M[2]]: [N, navigator.appVersion, '-?'];

        return M;
    })();
    var version = parseInt(navigator.sayswho[1]);
         
   if(navigator.userAgent.match(/firefox/i) == 'Firefox')
    {
        if(version<5)
            window.location.href = "<?php echo $baseUrl."/index/browserfailure";?>";
    }
    else if(navigator.userAgent.match(/msie/i) == 'MSIE')
    {        
         if(version<8)      
            window.location.href = "<?php echo $baseUrl."/index/browserfailure";?>";
    }
    else if(navigator.userAgent.match(/chrome/i) == 'Chrome')
    {
       if(version<13)
            window.location.href = "<?php echo $baseUrl."/index/browserfailure";?>";
    }
    else if(navigator.userAgent.match(/safari/i) == 'Safari' && navigator.userAgent.match(/Android/i) != 'Android')
    {
       if(version<5)
            window.location.href = "<?php echo $baseUrl."/index/browserfailure";?>";
    }
    else if(navigator.userAgent.match(/opera/i) == 'Opera')
    {
       if(version<12)
            window.location.href = "<?php echo $baseUrl."/index/browserfailure";?>";
    } 
        
  });   

<?php } ?>
</script>



</head>
	<body class="reports_body tm_body sf_assets">
		<input type= "hidden" value= "<?php echo $baseUrl;?>" id = "baseurl" />
		<input type= "hidden" value= "<?php echo DATEFORMAT_JS;?>" id = "dateformatjs" />
		<input type= "hidden" value= "<?php echo $tourflag;?>" id = "take-tour-flag" />
		<input type= "hidden" value= "<?php echo $loginUserId;?>" id = "loginuserId" name = "loginuserId" />
		<input type= "hidden" value= "" id = "dragid" />

		<script type="text/javascript"> 
		    var base_url = "<?php echo $baseUrl;?>";
		    var msg = '';  
		    var loginUserId = $('#loginuserId').val();
		    var domain_data = "<?php echo DOMAIN;?>";
		    var management_group = "<?php echo MANAGEMENT_GROUP;?>";
		    var superAdmin_id = "<?php echo SUPERADMIN;?>";
		    var clicked = '';		
		</script>

<?php if($actionName !='browserfailure'){ ?> 
    <div id='mainDiv' align="center" >
        <div id="main-div">
            <div id="page-container">        
            <!-- Header Part Starts-->
                <div id="header">					
<?php   if($auth->hasIdentity())
        { 							
            $organizationImg = new Zend_Session_Namespace('organizationinfo');
            $hideshowmainmenu = $organizationImg->hideshowmainmenu;
            $orgLogoImg = MEDIA_PATH.'images/hrms-logo-new.png';
            if(isset($organizationImg->orgimg) && !empty($organizationImg->orgimg))
            {
                $orgLogoImg = DOMAIN.'public/uploads/organisation/'.$organizationImg->orgimg ; 
            }
?>
            <a href="<?php echo $baseUrl;?>" style="text-decoration:none;" class="logo">
                <img src="<?php echo $orgLogoImg; ?>" onerror="this.src='<?php echo MEDIA_PATH; ?>images/hrms-logo-new.png'">
            </a> <!-- added by sapplica -->
            <div class="links">
			
			
				
				
				
                <a class="userprofilepic" id="logoutbutton"> 
                <i>
                    <img class="js_profile_img" id="profile_img" width="28" height="28" border="0" src="<?php echo $loginProfileImgSrc;?>" />
                </i>
                <span id="prof_name" title="<?php echo $userfullname; ?>">
                	<?php if(strlen($userfullname)>14){ echo substr($userfullname, 0, 14).'..'; } else {echo $userfullname;}?>
                </span>
                <b id="b_id" ></b>							
                </a>
                <div class="logoutdiv" id="logoutid" style="display:none">
                <div class="arrow-div"></div>
                <a href="<?php echo $baseUrl; ?>/dashboard/viewprofile" class="first">View Profile</a>
                <a href="<?php echo $baseUrl; ?>/viewsettings/1">Settings</a>                                                        
                <a href="<?php echo $baseUrl; ?>/dashboard/changepassword">Change Password</a>
<?php 
if($loginuserRole == SUPERADMINROLE)
{
?>
        <a href="<?php echo $baseUrl; ?>/dashboard/emailsettings">Mail Settings</a>
<?php 
}
if($loginuserRole == SUPERADMINROLE)
{
?>
	<a href="<?php echo $baseUrl; ?>/dashboard/upgradeapplication">Upgrade Application</a>
<?php }?>	
    <a href="<?php echo $baseUrl; ?>/index/logout">Logout</a>
        </div>
    </div>
            <?php if($loginuserRole == SUPERADMINROLE)
				{?>
					<div class="configurewizard"> 
						<a href="<?php echo $baseUrl; ?>/wizard" id="configwizard">Configuration Wizard</a>
					</div>
			<?php } ?>
								
            
<?php } //endif; ?>  

		<div id="themes_id" style="position:relative; float:right; margin-right:15px; display:none;">
			<div class="themes_iconnor">Themes</div>
		
			<div id="themes_div" style="display: none;" class="themesbg">
				<div class="themes_icon">Themes</div>
			  	<div class="themes_spritediv">
				    <span class="themes_sprite blue" title="Blue" onclick="javascript:setTheme('default');"></span>
				    <span class="themes_sprite brown" title="Brown" onclick="javascript:setTheme('brown');"></span>
				    <span class="themes_sprite gray" title="Gray" onclick="javascript:setTheme('gray');"></span>
				    <span class="themes_sprite skyblue" title="Skyblue" onclick="javascript:setTheme('skyblue');"></span>
				    <span class="themes_sprite peacock" title="Peacock" onclick="javascript:setTheme('peacock');"></span>
					<span class="themes_sprite green" title="Green" onclick="javascript:setTheme('green');"></span>
				    <span class="themes_sprite orange" title="Orange" onclick="javascript:setTheme('orange');"></span>
				</div>
		  	</div>
	 	</div>
                                    
</div>
                            <!-- Header End here-->		           
<div id="content"><div class="tour_aboutHrms"></div>            
<div class="content_inners">
<div id="container">
    <div id="spinner" class="ajax-loader" style="display:none;" >
    <img id="img-spinner" src="<?php echo MEDIA_PATH;?>images/loader2.gif" alt="Loading" />				
</div>
<div id="wrapper"> 
    <div class="wrapperdiv">	
	    <div class="wrapperdivright" style="width:100%;">
		    <div id="breadcrumdiv">
		    	  <div class="breadcrumbs">
		            <span onclick="window.location='<?php echo $baseUrl; ?>'" class="firstbreadcrumb">Home</span> 
		            <span class="arrows">&rsaquo;</span>
		            <a href="<?php echo $baseUrl; ?>/assets/assets/">Asset </a>
		        </div> 
  			</div>
  			<div class="back-page-div-report" style = "right: 26px;top: 9px;">
			<a href="<?php echo $baseUrl; ?>/welcome" class="sprite reports-back-btn " style="float:left;">Back to Dashboard</a>
			<a target="_blank" href="<?php echo DOMAIN; ?>public/downloads/time.pdf" class="importformatlink flt_left" style="margin-top:-4px;">Help</a>
			</div>
			<div class="notification_icon" style = "right: 200px;top: 9px;">
				<?php if(Zend_Registry::get( 'tm_role' )=='Employee') { 
					if(isset($display_dates_array) && count($display_dates_array)>0 && !($employeeDOJ['date_of_joining']>=$week_start && $employeeDOJ['date_of_joining']<=$week_start)) { 
				?>
				<a href="<?php echo $baseUrl; ?>/timemanagement/notifications/index"><i class="fa fa-bell"></i> <span class="notif_count_txt">(<?php echo count($display_dates_array);?>)</span></a>
				<?php } ?>
				<?php } ?>
			
			</div>

    <div id="maincontentdiv" class="reports-block-area">	
        <div id="dialog-confirm" style="display:none;">
            <div class="newframe-div">
                <div class="new-form-ui height32">
                    <div class="division">
                        <input type="text" maxlength="10"  id="number_value" name="number_value">
                    </div>
                    <span class="errors" id="errors-contactnumber"></span>
                </div>
            </div>
        </div>
    									
        <div id="empstatus-alert" style="display:none;">
            <div class="newframe-div"><div id="empstatusmessage"></div></div>
        </div>
    									
        <div id="empleaves-alert" style="display:none;">
            <div class="newframe-div"><div id="empleavesmessage"></div></div>
        </div>									
<?php } ?>
<div class="menu-head ">
      

<ul class="reports-ctrl" id="scroller">
	<li class="reports-div" id="assetsli"><a href="<?php echo $this->baseUrl("/index.php/assets/assets/");?>"><span class="menu_icon"><i class="fa fa-users fa-2"></i></span><p class="one-line">Assets </p></a></li>

	<li class="reports-div active" id="assetcategoriesli"><a href="<?php echo $this->baseUrl("/index.php/assets/assetcategories/");?>"><span class="menu_icon"><i class="fa fa-calendar fa-2"></i></span><p class="one-line">Asset Category</p></a></li>
</ul>

	<!-- Trigger -->
    <div class="dt_btn acv" id="assetCatView">
        <a class='dropdown-button' onclick ="window.location.href='<?php echo BASE_URL; ?>assets/assetcategories/edit'" data-activates='addbtn'>
            <i class="fa fa-plus"></i> Add
        </a>
    </div>
    
    <!-- Trigger -->
    <div class="dt_btn av" id="assetView">
        <a class='dropdown-button' onclick ="window.location.href='<?php echo BASE_URL; ?>assets/assets/edit'" data-activates='addbtn'>
            <i class="fa fa-plus"></i> Add
        </a>
    </div>
</div>

 
<div class="reports-grid-ctrl">
<div class="chart-ctrl">        


<!-- div id="video_tut_dialog" style="display: none;" > 
	<video id="the-video" width="580" height="400" preload="" controls="">
	  	  <source src="<?php // echo MEDIA_PATH; ?>timemanagement/tmvideo.mp4"  type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
		  <source src="<?php // echo MEDIA_PATH; ?>timemanagement/tmvideo.ogv" type='video/ogg; codecs="theora, vorbis"'>
	</video>
</div> -->                                                                         
  			