<?php
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2015 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/ 
?>

<?php if($actionName !='browserfailure'){ ?> 	
					</div>		            
		         <div style="clear: both;"></div>
               </div>
    </div>

<script type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/jquery.form_3.39.js"></script><!-- added on 07-aug-2013 by rama krishna -->
<script type="text/javascript" src="<?php echo MEDIA_PATH; ?>jquery/js/jquery.blockUI_2.64.js"></script><!-- added on 07-aug-2013 by rama krishna -->
<script type="text/javascript" language="javascript">
$(document).ready(function() {
 /* Making window responsive*/
 	var complete_empwidth = $('.emp-screen-view').width();
	$('#displayimg').css("width", "150");
	$('#personalDetailsDiv').css("width", (complete_empwidth-(152)));	
		
	 function checkempWidth() {
        var complete_empwidth = $('.emp-screen-view').width();		
		$('#displayimg').css("width", "150");
		$('#personalDetailsDiv').css("width", (complete_empwidth-(152)));		
    }
	
	/* Making window responsive*/
 	var complete_width = $('.poc-ui-data-control').width();
	$('.left-block-ui-data').css("width", "230");
	$('.right-block-data').css("width", (complete_width-(263)));	
		
	 function checkWidth() {
        var complete_width = $('.poc-ui-data-control').width();		
		$('.left-block-ui-data').css("width", "230");
		$('.right-block-data').css("width", (complete_width-(263)));		
    }
	
	
	function checknew1Width() {
        var complete_width = $('.short-ui-full-1').width();		
		$('.short-ui-full-1 label').css("width", "160");
		$('.short-ui-full-1 .division1').css("width", (complete_width-(190)));	
    }

	/* Making window responsive*/
 	var complete_width = $('.short-ui-full-1').width();
	$('.short-ui-full-1 label').css("width", "160");
	$('.short-ui-full-1 .division1').css("width", (complete_width-(190)));	
	
	 
	$(window).resize(function() {
		checkWidth();
		checkempWidth();
		checknew1Width();
	});

	//$('.step_form').alternateScroll({ 'horizontal-bar-class': 'styled-h-bar'});
	
});	
	
</script>



<?php 

}else { ?>
<link rel="stylesheet" type="text/css" href="<?php echo MEDIA_PATH; ?>css/loginstyle.css" />
<footer>
	<div class="footer-text">&copy; <?php echo APPLICATION_NAME; ?>, All Rights Reserved.</div>
</footer> 
<?php } ?>
</body>
</html>