<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if($this->popup == 'close') { ?>	
	<div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
	Vendor <?php echo $this->eventact; ?> successfully.
	</div>

	<?php } 
else
{
sapp_Global::generateClientValidations($this->form);?>
<div id="error_message" style="display:none;"></div>

<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller">
		
		
		
		<div class="new-form-ui inputheight-4">
        <label class="required"> Name</label>
        <div class="division"><?php echo $this->form->name; ?></div>
        <?php if(isset($this->msgarray['name'])){?>
				   <span class="errors" id="errors-name"><?php echo $this->msgarray['name'];?></span>
		<?php }?>
    </div>
		    
		<div class="new-form-ui inputheight-4">
        <label class="required">Contact Person</label>
        <div class="division"><?php echo $this->form->contact_person; ?></div>
        <?php if(isset($this->msgarray['contact_person'])){?>
				   <span class="errors" id="errors-contact_person"><?php echo $this->msgarray['contact_person'];?></span>
		<?php }?>
    </div>
		
<div class="new-form-ui textareaheight">
					  <label> Address </label>
					<div class="division"><?php echo $this->form->address; ?></div>
					</div>
			
			<div class="new-form-ui">
        <label  class="required">Country</label>
        <div class="division"><?php echo $this->form->country; ?>
		<?php if(isset($this->msgarray['country'])){?>
				   <span class="errors" id="errors-country"><?php echo $this->msgarray['country'];?></span>
		<?php }?>
       
        </div>
    </div>
    <div class="new-form-ui">
        <label class="required">State</label>
        <div class="division"><?php echo $this->form->state; ?>
		<?php if(isset($this->msgarray['state'])){?>
				   <span class="errors" id="errors-state"><?php echo $this->msgarray['state'];?></span>
		<?php }?>
       
        </div>
    </div>
    <div class="new-form-ui">
        <label class="required">City</label>
        <div class="division"><?php echo $this->form->city; ?>
		<?php if(isset($this->msgarray['city'])){?>
				   <span class="errors" id="errors-city"><?php echo $this->msgarray['city'];?></span>
		<?php }?>
       
        </div>
    </div>
	 <div class="new-form-ui">
        <label class="required">Pin Code</label>
        <div class="division"><?php echo $this->form->pincode; ?></div>
		<?php if(isset($this->msgarray['pincode'])){?>
				   <span class="errors" id="errors-pincode"><?php echo $this->msgarray['pincode'];?></span>
		<?php }?>
    </div>   
<div class="new-form-ui">
        <label class="required">Primary Phone</label>
        <div class="division"><?php echo $this->form->primary_phone; ?></div>
		<?php if(isset($this->msgarray['primary_phone'])){?>
				   <span class="errors" id="errors-primary_phone"><?php echo $this->msgarray['primary_phone'];?></span>
		<?php }?>
    </div>
			
			
	<div class="new-form-ui">
        <label>Secondary Phone</label>
        <div class="division"><?php echo $this->form->secondary_phone; ?></div>
		<?php if(isset($this->msgarray['secondary_phone'])){?>
				   <span class="errors" id="errors-secondary_phone"><?php echo $this->msgarray['secondary_phone'];?></span>
		<?php }?>
    </div>	
    	
		<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="closeiframepopup('<?php echo $this->controllername;?>','cancel');" type="button" >Cancel</button>
		</div>
</div>
</form>
<?php }?>

<script language='javascript' type='text/javascript'>

	<?php if($this->popup != '') { ?>
	setTimeout(function(){
	  closeiframeAddPopup("<?php echo $this->vendorData ;?>",'<?php echo $this->controllername; ?>','vendor','Vendor'); 					
},2000);

	<?php } ?>
	</script>
<script type='text/javascript'>
	$(document).ready(function() { 
		<?php if (count($this->messages)) {?>
			  setTimeout(function(){
					$('#popupmessage').fadeOut('slow');
				},3000);

		<?php } ?>
	});
</script>