<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
	$form = $this->form;
sapp_Global::generateClientValidations($form);?>
<div id="error_message" style="display:none;"></div>


<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
        <div class="total-form-controller">
		
		
		
		<div class="new-form-ui inputheight-4">
        <label class="required"> Name</label>
        <div class="division"><?php echo $form->name; ?></div>
        <?php if(isset($this->msgarray['name'])){?>
				   <span class="errors" id="errors-name"><?php echo $this->msgarray['name'];?></span>
		<?php }?>
    </div>
		    
		<div class="new-form-ui inputheight-4">
        <label class="required">Contact Person</label>
        <div class="division"><?php echo $form->contact_person; ?></div>
        <?php if(isset($this->msgarray['contact_person'])){?>
				   <span class="errors" id="errors-contact_person"><?php echo $this->msgarray['contact_person'];?></span>
		<?php }?>
    </div>
		
<div class="new-form-ui textareaheight">
					  <label> Address </label>
					<div class="division"><?php echo $this->form->address; ?></div>
					</div>
			
			<div class="new-form-ui">
        <label  class="required">Country</label>
        <div class="division"><?php echo $form->country; ?>
		<?php if(isset($this->msgarray['country'])){?>
				   <span class="errors" id="errors-country"><?php echo $this->msgarray['country'];?></span>
		<?php }?>
        <?php if(in_array('country',$this->popConfigPermission)) { ?>	
			<span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL.'countries/addnewcountry' ?>','Country');"> Add Country</span>			
		<?php } ?>
        </div>
    </div>
    <div class="new-form-ui">
        <label class="required">State</label>
        <div class="division"><?php echo $form->state; ?>
		<?php if(isset($this->msgarray['state'])){?>
				   <span class="errors" id="errors-state"><?php echo $this->msgarray['state'];?></span>
		<?php }?>
        <?php if(in_array('state',$this->popConfigPermission)) { ?>	
			<span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL.'states/addnewstate' ?>','State');"> Add State</span>			
		<?php } ?>
        </div>
    </div>
    <div class="new-form-ui">
        <label class="required">City</label>
        <div class="division"><?php echo $form->city; ?>
		<?php if(isset($this->msgarray['city'])){?>
				   <span class="errors" id="errors-city"><?php echo $this->msgarray['city'];?></span>
		<?php }?>
        <?php if(in_array('city',$this->popConfigPermission)) { ?>	
			<span class="add-coloum" onclick="displaydeptform('<?php echo BASE_URL.'cities/addnewcity' ?>','City');"> Add City</span>			
		<?php } ?>
        </div>
    </div>
	 <div class="new-form-ui">
        <label class="required">Pin Code</label>
        <div class="division"><?php echo $form->pincode; ?></div>
		<?php if(isset($this->msgarray['pincode'])){?>
				   <span class="errors" id="errors-pincode"><?php echo $this->msgarray['pincode'];?></span>
		<?php }?>
    </div>   
<div class="new-form-ui">
        <label class="required">Primary Phone</label>
        <div class="division"><?php echo $form->primary_phone; ?></div>
		<?php if(isset($this->msgarray['primary_phone'])){?>
				   <span class="errors" id="errors-primary_phone"><?php echo $this->msgarray['primary_phone'];?></span>
		<?php }?>
    </div>
			
			
	<div class="new-form-ui">
        <label>Secondary Phone</label>
        <div class="division"><?php echo $form->secondary_phone; ?></div>
		<?php if(isset($this->msgarray['secondary_phone'])){?>
				   <span class="errors" id="errors-secondary_phone"><?php echo $this->msgarray['secondary_phone'];?></span>
		<?php }?>
    </div>		
			
			<div class="new-form-ui-submit">
		<?php echo $this->form->submit; ?>
		<button onclick="window.location.href='<?php echo BASE_URL; ?>vendors';" type="button" id="Cancel" name="Cancel">Cancel</button>
		</div>
</div>
</form>
<div id="countriesContainer"  style="display: none; overflow: auto;">
			<div class="heading">
				<a href="javascript:void(0)">
				<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right"
					border="0" hspace="3" vspace="5" class="closeAttachPopup"
					style="margin: -24px 8px 0 0;"> </a>
			</div>

				<iframe id="countriesCont" class="business_units_iframe" frameborder="0"></iframe>

		</div>
		
		<div id="statesContainer"  style="display: none; overflow: auto;">
			<div class="heading">
				<a href="javascript:void(0)">
				<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
			</div>

			<iframe id="statesCont" class="business_units_iframe" frameborder="0"></iframe>
		</div>  

		<div id="citiesContainer"  style="display: none; overflow: auto;">
			<div class="heading">
				<a href="javascript:void(0)">
				<img src="<?php echo $this->baseUrl().'/public/media/';?>images/close.png" name="" align="right" border="0" hspace="3" vspace="5" class="closeAttachPopup" style="margin: -24px 8px 0 0;"> </a>
			</div>

			<iframe id="citiesCont" class="business_units_iframe" frameborder="0"></iframe>
		</div> 
<?php } 	?>