<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if (count($this->messages)) {?>
	<div id="dispmsgncc">
    
		<?php foreach ($this->messages as $message){?>
		<?php if(!empty($message['deleteflag']) && $message['deleteflag']==1){?>
		
		<?php if($message['msgtype'] == 'error')
		{?>
			<div class="ml-alert-1-error">
			<div class="style-1-icon error"></div>
			<?php echo $message['error'];?>
			</div>
		<?php }else{ ?>
			<div class="ml-alert-1-success">
			<div class="style-1-icon success"></div>
			<?php echo $message['success'];?>
			</div>
		<?php }
		}else{
		?>
			<div class="ml-alert-1-success">
			<div class="style-1-icon success"></div>
		<?php echo $this->escape($message); ?>
	</div>
		<?php } 
	}?>
    
	</div>	
	
<?php } ?>
<span id="error_message"></span>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
?>

<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgncc').fadeOut('slow');
		},3000);
<?php } ?>
})
</script>
