<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; 
$msgtitle = $this->controllername.'_delete';
sapp_Helper::editdeleteForView(VENDORS,$this->controllername,$this->id,$msgtitle); ?>
<?php
 $name = $this->form->name->getValue();
 $country = $this->form->country->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Name',(!empty($name))?$this->form->name->getValue():"...",'Contact Person',(!empty($this->data['contact_person']))?$this->data['contact_person']:"...");
sapp_Helper::viewBody('nor','Address',(!empty($this->data['address']))?$this->data['address']:"...",'Country',(!empty($country))?$this->form->country->getValue():"...");
sapp_Helper::viewBody('alt','State',(!empty($this->data['state']))?$this->data['state']:"...",'City ',(!empty($this->data['city']))?$this->data['city']:"...");
sapp_Helper::viewBody('nor','Pin Code',(!empty($this->data['pincode']))?$this->data['pincode']:"...",'Primary Phone',(!empty($this->data['primary_phone']))?$this->data['primary_phone']:"..."); 
sapp_Helper::viewBody('alt','Secondary Phone',(!empty($this->data['secondary_phone']))?$this->data['secondary_phone']:"...",'','');
sapp_Helper::viewFooter();
?>

       
	<!--	<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php //echo $this->controllername;?>',<?php //echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php //echo BASE_URL; ?>vendors';" type="button" >Cancel</button>
		</div> -->
        
<?php	}	?>