<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
        <div class="total-form-controller view-form-detail">
		 	<div class="new-form-ui ">
			  <label id="injuredDate">Skill</label>
				<div class="division loca_state_div"><?php echo $this->form->skillname; ?></div>
			</div>
			
			<div class="new-form-ui ">
				<label>Years of Experience</label>
				<div class="division"><?php echo $this->form->yearsofexp; ?></div>
			</div>
			
			<div class="new-form-ui ">
			    <label>Competency Level</label>
				<div class="division"><?php echo $this->form->competencylevelid; ?></div>
			</div>

			<div class="new-form-ui ">
			<label >Skill Last Used Year</label>
			<div class="division"><?php echo $this->form->year_skill_last_used; ?></div>
			</div>

        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empskills','cancel');" type="button" value="Close"  />
        </div>
 

</div>       
        