<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$form = $this->form;

?>
<?php 
$reportingManagerData = $this->reportingManagerData;
if($this->ermsg == '')  { ?>
<div class="requisitions-block">
<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
    <?php
    if($this->previ_data == 'Yes')
    {
    ?>
    <div class="edit-btn">
        <div class="new-form-ui-submit ">
            <input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />        
        </div>
    </div>
    <?php 
    }
    ?>
<div class="separetor-heading">Requisition Details</div>

<table width="100%" border="0" cellspacing="0" cellpadding="0" class="requisition-table">

<tr class="req-bg-form">
<td width="20%">Requisition ID <b>:</b></td>
<td width="30%"><?php echo $this->data['requisition_code'];?></td>
<td width="20%">Job Title <b>:</b></td>
<td width="30%"><?php echo $this->data['titlename'];?></td>
</tr>

<tr  class="req-no-form">
<td>Due Date <b>:</b></td>
<td><?php echo $this->data['onboard_date'];?></td>
<td>Business Unit <b>:</b></td>
<td><?php echo $this->data['businessunit_name'];?></td>
</tr>

<tr class="req-bg-form">
<td>Department <b>:</b></td>
<td><?php echo $this->data['dept_name'];?></td>
<td>Position <b>:</b></td>
<td><?php echo $this->data['posname'];?></td>
</tr>

<tr class="req-no-form">
<td>Reporting Manager <b>:</b></td>
<td><?php echo $this->data['mngrname'];?></td>
<td>Priority <b>:</b></td>
<td><?php if($this->data['req_priority'] == 1) echo 'High';
				else if($this->data['req_priority'] == 2) echo 'Medium';
				else echo 'Low'; ?></td>
</tr>

<tr class="req-bg-form">
<td>Employment Status <b>:</b></td>
<td><?php echo $this->data['empttype'];?></td>
<td valign="top">Req. Qualification <b>:</b></td>
<td><?php echo $this->data['req_qualification'];?></td>
</tr>

<tr class="req-no-form">
<td>Req. Experience Range <b>:</b></td>
<td><?php echo $this->data['req_exp_years'];?> year(s)</td>
<td>Req. no. of Positions <b>:</b></td>
<td><?php echo $this->data['req_no_positions'];?></td>
</tr>

<tr class="req-bg-form">
<td>Filled. no. of Positions <b>:</b></td>
<td><?php echo $this->data['filled_positions'];?></td>
<td>Raised By <b>:</b></td>
<td><?php echo ucfirst($this->data['raisedby']);?></td>
</tr>
<tr class="req-no-form">
<td>Approver -1 <b>:</b></td>
<td><?php echo ucfirst($this->data['app1_name']);?></td>
<td>Approver -2 <b>:</b></td>
<td><?php echo ucfirst($this->data['app2_name']);?></td>
</tr>
<tr class="req-bg-form no-border">
<td>Approver -3 <b>:</b></td>
<td><?php echo ucfirst($this->data['app3_name']);?></td>
<td></td><td></td>
</tr>
</table>
    <div class="separetor-heading mrgetop10">Job Details</div>
      
    <div class="form-ui-full bg-form">
        <label>Job Title<b>:</b></label>
        <div class="division"><?php echo $this->data['titlename'];?>
        </div>
    </div>
      
    <div class="form-ui-full">
        <label>Job Description<b>:</b></label>
        <div class="division"><?php echo $this->data['jobdescription'];?>
        </div>
    </div>
    <div class="form-ui-full bg-form">
        <label>Required Skills<b>:</b></label>
        <div class="division"><?php echo $this->data['req_skills'];?>
        </div>
    </div>
   
   <div class="form-ui-full no-border">
        <label>Additional Information<b>:</b></label>
        <div class="division"><?php echo $this->data['additional_info'];?>
        </div>
    </div>
   
</div>
</div>
<script type='text/javascript'>
$(document).ready(function(){
	/* Making window responsive*/
 	var complete_width = $('.form-ui-full').width();
	$('.form-ui-full label').css("width", "160");
	$('.form-ui-full .division').css("width", (complete_width-(190)));	
		
	 function checkWidth() {
        var complete_width = $('.form-ui-full').width();		
		$('.form-ui-full label').css("width", "160");
		$('.form-ui-full .division').css("width", (complete_width-(190)));		
    }
	$(window).resize(function() {
		checkWidth();
	}); 
});
</script>
<?php } else { ?>No data found.<?php } ?>

<?php 
}
?>