<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php //if($this->rowexist == 'norows'){?>
				<!--No record exists-->
				No data found.
				<?php //}else{?>
				
				<?php //}?>
	</div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
			<!--<div class="new-form-ui clearb">
			  <label class="required">Business Unit</label>
			<div class="division"><?php //echo $this->form->busineesunitid; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label class="required">Department</label>
			<div class="division loca_state_div"><?php //echo $this->form->departmentid; ?></div>
			</div>-->
			
			<div class="new-form-ui clearb">
			  <label>Job Title</label>
			<div class="division"><?php echo $this->form->jobtitleid; ?></div>
			</div>
			
			<div class="new-form-ui clearb">
			  <label>Position </label>
			<div class="division"><?php echo $this->form->positionname; ?></div>
			</div>
								
			<div class="new-form-ui clearb textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
	
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<!--<input type="submit" onclick="changestatus('<?php //echo $this->controllername;?>',<?php //echo $this->id;?>,'');" value="Delete" />-->
			<button onclick="window.location.href='<?php echo $this->baseUrl();?>/positions';" type="button" >Cancel</button>
		</div>
</div>     
<?php	}	?>   