<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
		    <div class="new-form-ui clearb">
			  <label>Name</label>
			<div class="division"><?php echo $this->form->name; ?></div>
			</div> 
			<div class="new-form-ui clearb">
			  <label>Contact Person </label>
			<div class="division"><?php echo $this->form->contact_person; ?></div>
			</div>
			<div class="new-form-ui clearb textareaheight">
			  <label>Address</label>
			<div class="division"><?php echo $this->form->address; ?></div>
			</div>
			<div class="new-form-ui">
					  <label>Country</label>
					<div class="division"><?php echo $this->form->country;?></div>
					</div>
		   <div class="new-form-ui">
					  <label>State</label>
					<div class="division"><?php echo $this->form->state;?></div>
		       </div>
					
					<div class="new-form-ui">
					  <label>City</label>
					<div class="division"><?php echo $this->form->city;?></div>
					</div>
					<div class="new-form-ui">
					  <label>Pin Code</label>
					<div class="division"><?php echo $this->form->pincode;?></div>
					</div>
			<div class="new-form-ui clearb textareaheight">
			  <label>Primary Phone</label>
			<div class="division"><?php echo $this->form->primary_phone; ?></div>
			</div>
			<div class="new-form-ui clearb textareaheight">
			  <label>Secondary Phone</label>
			<div class="division"><?php echo $this->form->secondary_phone; ?></div>
			</div>
		<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php echo BASE_URL; ?>vendors';" type="button" >Cancel</button>
		</div>
</div>        
<?php	}	?>