<div class="edit_emp_docs_div">
	<div id="edit_error_message" style="display:none;"></div>
<?php $empDoc = $this->empDocuments;?>
			<div class="new-form-ui">
				<!--<label class="required">Document Name</label>-->
				<div class="division">
					<input type="text" id="edit_document_name" name="edit_document_name" maxlength="50" value="<?php echo $empDoc['name'];?>">
					<span id="errors-edit_document_name" class="errors"></span>
				</div>
			</div>
			<div class="new-form-ui-1" id="doc_attachment_edit">
		        
		        <div class="division">
		        	<span class="upload-attachment uploadbutsel" id="fileuploadedit">
		        		<b class="sprite upload-icon" style="cursor:pointer;">Upload Attachment</b>
		        	</span>
		        
			        <?php $new_val='';$ori_val='';if($empDoc['attachments']){
			        	$attachments = json_decode($empDoc['attachments'],true);
			        	if(count($attachments)>0){
			        		$new = array();$ori = array();
			        		foreach ($attachments as $k => $v){
			        			if (isset($v["new_name"]) && isset($v["original_name"])) {
									$new[] = $v["new_name"];
									$ori[] = $v["original_name"];
			        			}
							}
							
							$new_val = implode(',', $new);
							$ori_val = implode(',', $ori);

			        		for($i = 0; $i<count($ori);$i++){
								echo '<div class="ajax-file-upload-statusbar" id="x_file_'.$i.'">
										<div class="ajax-file-upload-filename" title="'.$ori[$i].'">'.$ori[$i].'</div>
										<div class="ajax-file-upload-red" onclick=deleteImages(this,"'.$ori[$i].'","'.$new[$i].'","x_file_'.$i.'") style="">x</div>
									  </div>';
							}
			        	}
			        }?>
		        
		        </div>
				<div id="loaderimgprofileedit" style="display:none;">
					<img src="<?php echo $this->baseUrl("public/media/images/loaderwhite_21X21.gif");?>" style="width:21px; height: 21px; float: none; "/>
				</div>
				<span id="errors-doc_attachment_edit" class="errors"></span>
			</div>
			<div class="new-form-ui-submit">
				<input type="hidden" name="edit_file_original_names" id="edit_file_original_names" value="<?php echo $ori_val;?>">
				<input type="hidden" name="edit_file_new_names" id="edit_file_new_names" value="<?php echo $new_val;?>">
				<input type="hidden" name="userid" id="userid" value="<?php echo $this->id;?>">
				<input type="hidden" name="doc_id" id="doc_id" value="<?php echo $empDoc['id'];?>">
				<input type="button" value="Update" onclick="updateEmpDoc();">
				<button onclick="toggleform('edit_emp_doc_<?php echo $empDoc['id'];?>');" type="button">Cancel</button>
			</div>
			<div class="clear"></div>
			</div>
<script type="text/javascript">

$("#fileuploadedit").uploadFile({
	url:base_url+"/employeedocs/uploadsave",
	fileName: "myfile",
    allowedTypes:"jpg,png,jpeg,gif,doc,docx,pdf,xls,xlsx,zip",	
    returnType:"json",
    formData: {doc_id:$('#doc_id').val()},
    showDelete:true,
    maxFileCount: 5,
    showFileCounter:false,
    duplicateStrict:true,
    showAbort:false,
    showDone:false,
    showCancel: false,
    uploadButtonClass:'upload-attachment',
    dragDrop:false,
    deletelStr:'x',
    dynamicFormData: function () {
        return {};
    },
    onSelect:function(files)
    {
    	$("#fileuploadedit_error").remove();
    	$("#loaderimgprofileedit").show();
    	var existing = $('#edit_file_original_names').val();
    	var existingArray = new Array(); 
    	var uploading_file_name = files[0].name; 
    	if(navigator.userAgent.match(/msie/i) == 'MSIE')
    		uploading_file_name = uploading_file_name.replace(/C:\\fakepath\\/i, '');

		// Avoid taking length when there are no existing attachment files in edit announcement
    	if (existing.length > 0) {
    		existingArray = existing.split(',');
    	}    		
    	var index = existing.indexOf(uploading_file_name);
    	var comma = uploading_file_name.indexOf(',');

    	for(var i = 0; i < files.length; i++)
		{    	
    		var uploading_file_name = files[i].name;
    		uploading_file_name = uploading_file_name.replace(/[^a-zA-Z0-9.]+/gi, '_');
    		var index = existing.indexOf(uploading_file_name);
        	var comma = uploading_file_name.indexOf(',');
	    	if (comma !== -1){
	    		$('#fileuploadedit').after('<div class="errors upload_error_x" id="fileuploadedit_error">Comma( , ) not allowed in file names.</div>');
	    		$("#loaderimgprofileedit").hide();
	    		return false;
	    	}
	    	var ext = uploading_file_name.split('.').pop();
	    	var arr = new Array('jpg','png','jpeg','gif','doc','docx','pdf','xls','xlsx','zip');
	    	if($.inArray(ext,arr) == -1){
	    		$("#loaderimgprofileedit").hide();
	    		$("#errors-doc_attachment_edit").html('');
	    	}
    	}
    	if (files.length > 5 || (existingArray.length + files.length) > 5) {
    		$('#fileuploadedit').after('<div class="errors upload_error_x" id="fileuploadedit_error">Maximum allowed files are: 5</div>');
    		$("#loaderimgprofileedit").hide();
            return false;
    	}
		return true;
    },
    onSuccess:function(files,data,xhr)
    {
    	$('.ajax-file-upload-error').not(':eq(0)').hide();
    	$(".ajax-file-upload-progress").hide();
    	if(navigator.userAgent.match(/msie/i) == 'MSIE')
    	{     
			var c = $('.ajax-file-upload-filename:first').html();
			var d = c.replace(/C:\\fakepath\\/i, '');
			$('.ajax-file-upload-filename:first').html(d);
    	}

    	// Show title of uploaded attahcment to users - for big named attachments
    	$(".ajax-file-upload-statusbar:first").attr('title', data.filedata.original_name);
    	
    	if (typeof data.filedata != 'undefined') {
        	$('#edit_file_original_names').val(($('#edit_file_original_names').val())?($('#edit_file_original_names').val()+','+data.filedata.original_name):data.filedata.original_name);
        	$('#edit_file_new_names').val(($('#edit_file_new_names').val())?($('#edit_file_new_names').val()+','+data.filedata.new_name):data.filedata.new_name);		
		} else if (typeof data.error != 'undefined') {

			// Validate file with size greater than default (Upload Max Filesize) limit
			if (data.error == 'filesize') {
				$("span#errors-doc_attachment_edit").html('Please enter file having size below 2MB.');
	    	} else if (data.error.length > 0) {
	    		$("span#errors-doc_attachment_edit").html('Something went wrong.');
	    	}
    		$('.ajax-file-upload-statusbar:first').remove();
		}    	
    	$("#loaderimgprofileedit").hide();
    },
    deleteCallback: function(data,pd)
	{
    	if(data){
    		$("#loaderimgprofileedit").show();
    		var doc_id = $("#doc_id").val();
	    	$.post(base_url+"/employeedocs/uploaddelete/format/json",{op: "delete", doc_new_name: data.filedata.new_name, doc_id: doc_id},
			        function(resp, textStatus, jqXHR)
			        {
		        		if(textStatus == 'success')
		        		{
				    		var x_original_files = $('#edit_file_original_names').val().split(',');
				    		var x_new_files = $('#edit_file_new_names').val().split(',');
	
				    		var org_index = x_original_files.indexOf(data.filedata.original_name);
				    		
				    		if (org_index !== -1) {
				    			x_original_files.splice(org_index, 1);
				    		    org_data = x_original_files.join(',');
				    		    $('#edit_file_original_names').val(org_data);
				    		}

				    		var new_index = x_new_files.indexOf(data.filedata.new_name);
				    		if (new_index !== -1) {
				    			x_new_files.splice(new_index, 1);
				    		    new_data = x_new_files.join(',');
				    		    $('#edit_file_new_names').val(new_data);
				    		}

				    		// Remove 'Download' button when there are no attachments
				    		if (x_original_files.length == 0) {
		    					$("#download_doc_" + doc_id).remove();
	    					}				    		
		        		}
			        });
	    	pd.statusbar.hide();
	    	$("#loaderimgprofileedit").hide();
    	}
    }
});
function deleteImages(event,original_name,new_name,div_id)
{
	$("#loaderimgprofileedit").show();
	var doc_id = $("#doc_id").val();
	$.post(base_url+"/employeedocs/uploaddelete/format/html",{op: "delete", doc_new_name: new_name, doc_id: doc_id},
    function(resp, textStatus, jqXHR)
    {
		if(textStatus == 'success')
		{
			$('#'+div_id).remove();
			
    		var x_original_files = $('#edit_file_original_names').val().split(',');
    		var x_new_files = $('#edit_file_new_names').val().split(',');

    		var org_index = x_original_files.indexOf(original_name);


    		// Update photo gallery by removed attachment
			$("#emp_docs_" + doc_id + " span.js_photo_gallery").html(resp);
			$("a[rel^='prettyPhoto']").prettyPhoto({social_tools : '', deeplinking: false});
    		
    		if (org_index !== -1) {
    			x_original_files.splice(org_index, 1);
    		    org_data = x_original_files.join(',');
    		    $('#edit_file_original_names').val(org_data);
    		}

    		var new_index = x_new_files.indexOf(new_name);
    		if (new_index !== -1) {
    			x_new_files.splice(new_index, 1);
    		    new_data = x_new_files.join(',');
    		    $('#edit_file_new_names').val(new_data);
    		}

    		// Remove 'Download' and 'View Attachments' buttons when there are no attachments
    		if (x_original_files.length == 0) {
				$("#download_doc_" + doc_id).remove();
				$("#emp_docs_" + doc_id + " a.js_click_view").remove();
			}    		
		}
    });
	$("#loaderimgprofileedit").hide();
}
</script>
