<?php
/*********************************************************************************
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php echo $this->form->id;
		echo $this->form->user_id;
		?>
<?php
$oncall_limit = $this->form->oncall_limit->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Oncall Limit',(!empty($oncall_limit))?$this->form->oncall_limit->getValue():"...",'Year',(!empty($this->data['alloted_year']))?$this->data['alloted_year']:"...");
sapp_Helper::viewFooter();
?>
			<div class="clearall usedoncalls">
				Used Oncalls : <?php echo $this->form->used_oncalls->getValue() ;?>
			</div>

			<div class="clearall oncallnames">
				<?php
					if(!empty($this->oncallTypeCount))
					{
						 foreach($this->oncallTypeCount as $key => $oncall)
						 {?>
						 <?php echo $oncall['oncalltype']?> <b>:</b> <?php echo $oncall['count'];?>
						 <?php if(sizeof($this->oncallTypeCount) != $key+1){?>,<?php }?>
			   <?php 	 }
					}
				?>
			</div>

        <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('emponcalls','cancel');" type="button" value="Close"  />


</div>
