<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{	
sapp_Global::generateClientValidations($this->form);
?>
<div id="error_message" style="display:none;"></div>
<form name="<?php echo $this->form->getName(); ?>" id="<?php echo $this->form->getId(); ?>" action="<?php echo $this->form->getAction();?>" method="<?php echo $this->form->getMethod(); ?>">
		<?php echo $this->form->id; ?>
  <div class="total-form-controller">
	    <div class="new-form-ui ">
		    <label class="required"><?php echo $this->form->expense_name->getLabel(); ?> </label>
			<div class="division"><?php echo $this->form->expense_name; ?>
			<?php if(isset($this->msgarray['expense_name'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->expense_name->getId(); ?>"><?php echo $this->msgarray['expense_name'];?></span>
			<?php }?>
			</div>
		</div>
		
		<div class="new-form-ui textareaheight">
		    <label class="required"><?php echo $this->form->expense_amount->getLabel(); ?> </label>
			<div class="division"><?php echo $this->form->expense_amount; ?></div>
		</div>
		
		
		
		<div class="new-form-ui">
		    <label class="required"><?php echo $this->form->expense_date->getLabel(); ?> </label>
			<div class="division"><?php echo $this->form->expense_date; ?>
			<?php if(isset($this->msgarray['expense_date'])){?>
			   <span class="errors" id="errors-<?php echo $this->form->expense_date->getId(); ?>"><?php echo $this->msgarray['expense_date'];?></span>
			<?php }?>
			</div>
		</div>
		
	
		
				
		
		
		
		<div class="new-form-ui-submit">
			<?php echo $this->form->submit; ?>
			<button onclick="window.location.href='<?php echo BASE_URL; ?>expenses/';" type="button" >Cancel</button>
		</div>
 </div>
</form>

<?php }?>
<script type="text/javascript" language="javascript">
$(document).ready(function(){
	$(".breadcrumbs").append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>expenses/'>Expenses</a><span class='arrows'>&rsaquo;</span><span><?php echo $this->inpage;?></span>");
	
	 var yearrange = <?php echo "'".YEAR.':'.date('Y')."'"; ?>;
	$('#expense_date').datepicker({
        showOn:'both',
		//minDate: 0,
	    //yearRange: yearrange,
        dateFormat: '<?php echo DATEFORMAT_JS;?>',
        buttonImage: "<?php echo $this->baseUrl("public/media/images/cal.jpg");?>",
        buttonImageOnly: true,
        buttonText: "",
        changeMonth: true,
        changeYear: true ,
        showButtonPanel: true ,
        onClose:function(){
        	/*  $(this).trigger('blur');
             var msg = "";
             if(this.id == 'to_date')
                 msg = "To date should be greater than From date.";
             else 
                 msg = "From date should be less than To date.";
             from_to_date_validation('from_date','to_date',this,msg); */
        }
		
    });	
	
	
});
</script>  
 