<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if (count($this->messages)) {?>
	<div id="dispmsgempleaves">
    <div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
		<?php foreach ($this->messages as $message){?>
		 <?php echo $this->escape($message); ?>
		<?php } ?>
        </div>
	</div>	
	
<?php } ?>
<span id="error_message"></span>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;

?>

<!--<div class="company-info-block">
<?php //if(empty($this->dataArray)){?>
      <div class="edit-btn"><a href='<?php //echo DOMAIN;?>leavemanagement/add'>Add</a></div>
	  <span class="nodatatext">Leave management is not yet set. click add to create Leave management</span>
<?php //}else{?>
      <div class="edit-btn"><a href='<?php //echo DOMAIN;?>leavemanagement/edit/id/<?php //echo $this->dataArray[0]["id"]; ?>'>Edit</a></div>
<table cellpadding="0" cellspacing="0" width="100%" border="0" >
<tr>
<td class="td-1" align="left" valign="top">
    <div class="company-info">
	      <label>Calender start month
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['month_name']; ?>
		  </span>
	</div>
    <div class="company-info alter-div">
	      <label>Week starts on 
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['day_name']; ?>
		</span>
    </div>
	<div class="company-info">
	      <label>Is saturday holiday?
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['satholiday']; ?>
		  </span>
	</div>
    <div class="company-info alter-div">
	      <label>Hours in a full day 
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['hours_day']; ?>
		</span>
    </div>
	<div class="company-info">
	      <label>Partial(Half) day requests?
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['halfday']; ?>
		  </span>
	</div>
	<div class="company-info alter-div">
	      <label>Allow balance transfers?
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['leavetransfer']; ?>
		</span>
    </div>
	<div class="company-info">
	      <label>Skip holidays?
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['skipholidays']; ?>
		  </span>
	</div>
	<div class="company-info alter-div">
	      <label>Description
		      <b>:</b>
		  </label>
		  <span><?php //echo $this->dataArray[0]['description']; ?>
		</span>
    </div>

</td>

</tr>
</table>
<?php //} ?>
</div>-->

<script>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgempleaves').fadeOut('slow');
		},3000);

<?php } ?>

});
</script>

