<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
		    <div class="new-form-ui">
			<label>Business Unit</label>
			<div class="division loca_state_div"><?php echo $this->form->businessunit; ?></div>
			</div>
			
		    <div class="new-form-ui">
			<label>Department</label>
			<div class="division loca_state_div"><?php echo $this->form->department_id; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Calendar Start Month</label>
			<div class="division"><?php echo $this->form->cal_startmonth; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Weekend 1</label>
			<div class="division loca_state_div"><?php echo $this->form->weekend_startday; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Weekend 2</label>
			<div class="division loca_state_div"><?php echo $this->form->weekend_endday; ?></div>
			</div>
			
			<!--<div class="new-form-ui">
			  <label>Is Saturday Holiday?</label>
			<div class="division"><?php //echo $this->form->is_satholiday; ?></div>
			</div>-->
			
			<div class="new-form-ui">
			  <label>Working Hours</label>
			<div class="division"><?php echo $this->form->hours_day; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Half Day Requests</label>
			<div class="division"><?php echo $this->form->is_halfday; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Allow Leave Transfers?</label>
			<div class="division"><?php echo $this->form->is_leavetransfer; ?></div>
			</div>
			
			<div class="new-form-ui">
			  <label>Skip Holidays?</label>
			<div class="division"><?php echo $this->form->is_skipholidays; ?></div>
			</div>
					
			<div class="new-form-ui textareaheight">
			  <label>Description</label>
			<div class="division"><?php echo $this->form->description; ?></div>
			</div>
			
			<div class="new-form-ui-submit">
			<?php if(($this->editpermission == 'Yes')) { ?>
					 <input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
					<button onclick="window.location.href='<?php echo BASE_URL; ?>leavemanagement';" id="Cancel" name="Cancel" type="button" >Cancel</button>
		   <?php }
		   else{
			?>
					<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>leavemanagement';" type="button"  value="Back"  />
    	    <?php } ?>
			
		</div>
       </div>
		
		
<?php } ?>		