<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 
if($this->nodata != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else 
{
$form = $this->form;

?>
<?php 
$reportingManagerData = $this->reportingManagerData;
if($this->ermsg == '')  { ?>
<div class="total-form-controller cancel-set data-view-details">
    <div class="position_rel">
       
   </div>
    <?php
    if($this->previ_data == 'Yes')
    {
    ?>
    <div class="edit-btn">
        <div class="new-form-ui-submit ">
            <input type="button" class="fltright" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />        
        </div>
    </div>
    <?php 
    }
    ?>
<div class="separetor-heading">Requisition Details</div>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Requisition Code ',(!empty($this->data['requisition_code']))?$this->data['requisition_code']:"...",'Job Title',(!empty($this->data['titlename']))?$this->data['titlename']:"...");
sapp_Helper::viewBody('nor','Due Date',(!empty($this->data['onboard_date']))?$this->data['onboard_date']:"...",'Business Unit',(!empty($this->data['businessunit_name']))?$this->data['businessunit_name']:"...");
sapp_Helper::viewBody('alt','Department',(!empty($this->data['dept_name']))?$this->data['dept_name']:"...",'Position',(!empty($this->data['posname']))?$this->data['posname']:"...");
sapp_Helper::viewBody('nor','Reporting Manager',(!empty($this->data['mngrname']))?$this->data['mngrname']:"...",'Priority',(!empty($this->data['req_priority']))?$this->data['req_priority']:"..."); 
sapp_Helper::viewBody('alt','Employment Status',(!empty($this->data['empttype']))?$this->data['empttype']:"...",'Req. Qualification ',(!empty($this->data['req_qualification']))?$this->data['req_qualification']:"...");
sapp_Helper::viewBody('nor','Req. Experience Range',(!empty($this->data['req_exp_years']))?$this->data['req_exp_years']:"...",'Req. no. of Positions',(!empty($this->data['req_no_positions']))?$this->data['req_no_positions']:"...");
sapp_Helper::viewBody('alt','Filled. no. of Positions',(!empty($this->data['filled_positions']))?$this->data['filled_positions']:"...",'Raised By',(!empty($this->data['raisedby']))?$this->data['raisedby']:"...");
sapp_Helper::viewBody('nor','Approver -1',(!empty($this->data['app1_name']))?$this->data['app1_name']:"...",'Approver -2',(!empty($this->data['app2_name']))?$this->data['app2_name']:"...");
sapp_Helper::viewBody('alt','Approver -3 ',(!empty($this->data['app3_name']))?$this->data['app3_name']:"...",'','');
sapp_Helper::viewFooter();
?>
<div class="separetor-heading mrgetop10">Job Details</div>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Job Title ',(!empty($this->data['titlename']))?$this->data['titlename']:"...",'Job Description',(!empty($this->data['jobdescription']))?$this->data['jobdescription']:"...");
sapp_Helper::viewBody('nor','Required Skills',(!empty($this->data['req_skills']))?$this->data['req_skills']:"...",'Additional Information',(!empty($this->data['additional_info']))?$this->data['additional_info']:"...");
sapp_Helper::viewFooter();
?>


</div>

<script type='text/javascript'>
$(document).ready(function(){
	/* Making window responsive*/
 	var complete_width = $('.form-ui-full').width();
	$('.form-ui-full label').css("width", "160");
	$('.form-ui-full .division').css("width", (complete_width-(190)));	
		
	 function checkWidth() {
        var complete_width = $('.form-ui-full').width();		
		$('.form-ui-full label').css("width", "160");
		$('.form-ui-full .division').css("width", (complete_width-(190)));		
    }
	$(window).resize(function() {
		checkWidth();
	}); 
});
</script>
<?php } else { ?>No data found.<?php } ?>

<?php 
}
?>