<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php $baseUrl = $this->serverUrl().$this->baseUrl();

?>
<div id="error_message" style="display:none;"></div>
<div class="poc-ui-data-control">

		<?php echo $this->form->id; ?>
        <div class="total-form-controller view-form-detail">
		 	<div class="new-form-ui">
			  <label id="injuredDate">Course Name</label>
				<div class="division loca_state_div"><?php echo $this->form->course_name; ?></div>
				
			</div>
			<div class="new-form-ui ">
			  <label>Course Level</label>
			  <div class="division"><?php echo $this->form->course_level; ?></div>
				
			</div>
			<div class="new-form-ui ">
				<label>Course Offered By</label>
				<div class="division"><?php echo $this->form->course_offered_by; ?></div>
				</div>
			<div class="new-form-ui textareaheight">
					  <label>Description</label>
					<div class="division"><?php echo $this->form->description; ?></div>
					</div>
		
			<div class="new-form-ui ">
			  <label>Certification Name</label>
			  <div class="division"><?php echo $this->form->certification_name; ?></div>
				</div>
														
			<div class="new-form-ui">
			  <label id="issuedDate">Issued Date</label>
			  <div class="division"><?php echo $this->form->issued_date; ?></div>
				</div>


        <div class="new-form-ui-submit" id="formSubmit">
        <input onclick="closeiframepopup('trainingandcertificationdetails','cancel');" type="button" value="close"  />
        </div>
  		</div>      
</form>

<script>
$(document).ready(function(){
	//To get the Calender image...
	var yearrange = <?php echo "'".date("Y", strtotime("-30 years")).':'.date('Y')."'"; ?>;

	$('#from_date,#to_date').datepicker({
					showOn:'both',
					maxDate: new Date, 
					yearRange: yearrange,
					//dateFormat: 'mm-dd-yy',
					dateFormat:"<?php echo DATEFORMAT_JS;?>",
					buttonImage: "<?php echo $this->baseUrl("public/media/images/cal.jpg");?>",
					buttonImageOnly: true,
					buttonText: "",
					changeMonth: true,
                                        showButtonPanel: true ,
					changeYear: true 
					//minDate: 1  
	});
	
	 });
	 $("#certification_name").blur(function()
	 {
		if( $("#certification_name").val() != "")
		{
			$("#issuedDate").addClass("required");
		}
		else
		{
			$("#issuedDate").removeClass("required");
		}
	 });
</script>