<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee deleted
				<?php }?>
	</div>

<?php	}	else	{
sapp_Global::generateClientValidations($this->form);?>
<?php if(!empty($this->employeedata)) 
{
	echo $this->employeedetails($this->employeedata,'view',$this->id);
 } ?>

<div class="right-block-data"> 
	<div id="error_message" style="display:none;"></div>
<?php if(empty($this->data)){?>
			<div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>Disability details are not configured yet.
			</div>
	<?php }else{?>	
	<?php echo $this->form->id; ?>
			<div class="total-form-controller cancel-set view-form-detail">
				<div class="new-form-ui">
				  <label>Disability Type</label>
				<div class="division"><?php echo $this->form->disability_type; ?></div>
				</div>
				<div class="new-form-ui">
				  <label>Disability <img class="tooltip" title="Accepts spaces, hyphens, numbers and characters" src="<?php echo $this->baseUrl().'/public/media/';?>images/help.png"></label>
				<div class="division"><?php echo $this->form->disability_name; ?></div>
				</div>
				
				<div class="new-form-ui textareaheight">
				  <label>Description/Reason</label>
				<div class="division"><?php echo $this->form->disability_description; ?></div>
				</div>
				
				<div class="new-form-ui" id="OtherdisabilityType" style="display:none;">
					<label>Other Disability Type</label>
					<div class="division"><?php echo $this->form->other_disability_type; ?></div>
				</div>
				
				<div class="new-form-ui-submit">
				<!--	<input onclick="window.location.href='/hrms/employee';" type="button" id="Cancel" name="Cancel"value="Back"/>-->
				</div>
			
			</div>  
<?php	}	?>
</div>	
</div>


<script type="text/javascript" language="javascript">
$(document).ready(function() {
  var disabilityType = $("#disability_type").val();
	if(disabilityType !="" && disabilityType == "other impairments")
	{	
		showdisabilityField('disability_type');
	}
	
	$("#disabilitydetails").addClass('active');
	$("#disabilitydetails").removeAttr("onclick");

});//end of ready function

</script>
<?php	}	?>
