<?php 
/********************************************************************************* 
 *  This file is part of Sentrifugo.
 *  Copyright (C) 2014 Sapplica
 *   
 *  Sentrifugo is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Sentrifugo is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with Sentrifugo.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  Sentrifugo Support <support@sentrifugo.com>
 ********************************************************************************/
?>

<?php 	
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>
<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
$data = $this->data;
 ?>
        <div class="total-form-controller view-form-detail">

		<div style="margin-left: 0px; padding-top: 0px; padding-bottom: 20px;  float: none;" class="cofig_title">Default Task
			<div style="margin-top: 0px; float: right; width: auto;" class="new-form-ui-submit ">
			
			
				<!--<div style="position: relative; float: right; top: 0px;" class="back-to-page">
					<input type="button" style="margin-right: 0px;" value="Back" name="Back" onclick="window.location.href='<?php //echo BASE_URL; ?>timemanagement/defaulttasks';">
				</div>
				<input type="button" class="fltright" onclick="window.location.href='<?php //echo BASE_URL; ?>timemanagement/defaulttasks/edit/id/<?php //echo $data[0]['id'];?>';" value="Edit" />-->
				<?php 
                $msgtitle = $this->controllername.'_delete';
                sapp_Helper::editdeleteForView('',$this->controllername,$data[0]['id'],$msgtitle,$isfromTM=1); ?>
				
			</div>
		 </div>
		
		<table width="100%" cellspacing="0" cellpadding="0" border="0" class="requisition-table view-table-data">
				<tbody>
				<tr class="req-bg-form">
					<td width="40%"><span class="head_txt">Default Task</span></td>
					<td width="60%"><?php echo $data[0]['task']; ?></td>					
				</tr>
			</tbody>
		</table>
</div>       
<?php	}	?> 
<script type="text/javascript" language="javascript">
$(document).ready(function(){
	$('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>timemanagement/defaulttasks'>Default Tasks</a><span class='arrows'>&rsaquo;</span><span>View</span>");
});
</script>  