
<div style='padding: 0; text-align: left; font-size:14px; font-family:Arial, Helvetica, sans-serif;'>		
    <h2 style='color:#555555;font-size:18px; margin:10px 0 10px 10px;text-align:center;width:100%;text-transform: uppercase; '>Notification</h2>		
    
	<span style='color:#3b3b3b;'>Hello <?php echo $this->to_name;?>,</span><br/>
	
	<div style='padding:20px 0 10px 0;'>		
		<?php echo $this->page?> : <a href="<?php echo $this->url_link?>"><?php echo $this->expense_name;?></a> has been <?php echo $this->status;?> by <?php echo $this->from_name;?>
	</div>
		

</div> 


	  

	  
